RedHatInsights/sources-api

- Dockerfile
- docker-assets/entrypoint
- docker-assets/run_rails_server
This allows us to more easily move building the database url out of
the secret
@agrare please review
> Use Dockerfile CMD to run the rails server

- db/migrate/20190313191654_add_application_type_display_name.rb
- db/seeds.rb
Two PRs were merged to -core after sources-api was extracted:
1. https://github.com/ManageIQ/topological_inventory-core/pull/118
2. https://github.com/ManageIQ/topological_inventory-core/pull/117
This syncs these two with sources
> Sync sources with topological-core

- app/controllers/api/v0/application_types_controller.rb
- app/controllers/api/v0/applications_controller.rb
- app/controllers/api/v0x1.rb
- config/routes.rb
- public/doc/swagger-2-v0.1.0.yaml
The models and db migrations were moved over but I forgot to move the controllers and routes
~~Depends on: https://github.com/ManageIQ/sources-api/pull/9~~
> Add controllers and routes for applications

- app/controllers/internal/v0/tenants_controller.rb
- app/controllers/internal/v0x1.rb
- app/models/tenant.rb
- config/routes.rb
- public/doc/swagger-2-v0.1.0.yaml
- spec/controllers/internal/v0x1/tenants_controller_spec.rb
- spec/swagger_spec.rb
Add a way to get a list of tenants on the internal route
Depends on:
https://github.com/ManageIQ/sources-api/pull/10
https://github.com/ManageIQ/sources-api/pull/9
> Add internal tenants controller

- .gitignore
- .openapi_generator_config.json
- lib/tasks/client_generate.rake
Copied over from TopologicalInventory API
> Add an openapi client generator

- db/seeds.rb
Extracted from https://github.com/ManageIQ/topological_inventory-core/pull/125
> Add "role" to source_type seeds.

- app/controllers/api/v1/authentications_controller.rb
- app/controllers/api/v1/endpoints_controller.rb
- app/controllers/api/v1/sources_controller.rb
- app/controllers/application_controller.rb
- lib/sources/api/exception.rb
- spec/controllers/api/v1x0/endpoints_controller_spec.rb
- spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/index_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/show_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/controllers/internal/v1x0/authentications_controller_spec.rb
- spec/controllers/internal/v1x0/tenants_controller_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/filter_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v1_redirect_spec.rb
- spec/spec_helper.rb
- spec/support/tenant_identity.rb
Just pull the tenant from the identity headers
> Don't need to use the extra tenant parameter

- lib/tasks/client_generate.rake
rake task for generating client in more languages, defaulting ruby
Same PR as https://github.com/ManageIQ/topological_inventory-api/pull/187
> Multilanguage client generator

- db/seeds.rb
according to UX: https://docs.google.com/document/d/1cE_sG6IdBW-cHCODjplbWzDldHDhsbW6Xyn--XQqNxQ/edit?ts=5cc0b425#heading=h.wqa0bh1el605
> Update source product_name according to UX.

- spec/requests/api/v1.0/sources_spec.rb
Updated the name missing spec tests as it is now being caught by the validator. Different error message is being returned.
> Updated the name attribute missing spec

- Jenkinsfile-smoke.groovy
This PR has to be reviewed by @bsquizz
> Add a smoke tests groovy - sources

- app/controllers/api/v1/applications_controller.rb
The create action for Application was missing its raise_event.
> Add missing raise_event for Applications create

- Jenkinsfile-smoke.groovy
This PR has to be reviewed by @bsquizz
> Update Jenkins smoke job

- spec/requests/api/graphql_controller.rb
- Updated the GraphQL specs to reflect the simplified query signature.
> Updated the GraphQL specs to reflect the simplified query signature.

- app/models/concerns/tenancy_concern.rb
- public/doc/openapi-3-v1.0.0.json
- spec/requests/api/graphql_controller_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
https://projects.engineering.redhat.com/browse/TPINVTRY-416
> Do not include `tenant` in any API responses

- app/controllers/application_controller.rb
- db/migrate/20190809154221_add_extra_jsonb_to_authentications.rb
- db/seeds.rb
- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
Adding azure source and ability to send authentication with {"extra": {"azure": {"tenant_id": "some id"}}}
> Add Azure source

- app/models/application_type.rb
- config/routes.rb
- public/doc/openapi-3-v1.0.0.json
- spec/requests/api/v1.0/application_types_spec.rb
> Add /api/v1.0/application_types/:id/sources

- app/controllers/application_controller.rb
Fixes Related to TPINVTRY-170
Depends on https://github.com/ManageIQ/manageiq-api-common/pull/87
> Use extracted request methods in ManageIQ::API::Common

- app/controllers/application_controller.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
Depends on https://github.com/ManageIQ/manageiq-api-common/pull/89
Related to TPINVTRY-186
> Use extracted methods

- docker-assets/run_rails_server
Don't run db:migrate and db:seed together
(cherry picked from commit c87a3e94f580e39db3305e6c889b8d47a4c04303)
> Don't run db:migrate and db:seed together

- lib/tasks/openapi_generate.rake
https://projects.engineering.redhat.com/browse/TPINVTRY-501
> Return `tenant` in applications response

- app/controllers/application_controller.rb
- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
- spec/requests/api/v1.0/sources_spec.rb
Fixes https://projects.engineering.redhat.com/browse/TPINVTRY-416
> Filter tenant and tenant_id params from create/update requests

- db/migrate/20191011124345_add_imported_to_sources.rb
- public/doc/openapi-3-v1.0.0.json
TPINVTRY-632
after UX discussion  we decided to have read-only column here, see comments and mockup in the ticket.
source api client https://github.com/ManageIQ/sources-api-client-ruby/pull/12
@miq-bot assign @agrare
> Add imported column to sources table

- db/seeds/source_types.rb
With UX, we decided to use switches (https://data-driven-forms.org/component-example/switch-field) instead of checkboxes.
@agrare
> Change checkboxes to switches in DDF schemas

- Gemfile
- app/controllers/application_controller.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/filter_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
Update to 2.0.0 of manageiq-api-common and fix all of the exceptions that fail with the new ExceptionHandler mixin
> Update to manageiq-api-common 2.0

- public/doc/openapi-3-v1.0.0.json
https://projects.engineering.redhat.com/browse/TPINVTRY-232
> Add 404 return to OpenAPI spec for collections

- spec/requests/api/v1.0/sources_spec.rb
Related to https://github.com/ManageIQ/manageiq-api-common/issues/121
> Add tests with null values

- spec/requests/api/v1.0/authentications_spec.rb
Depends on: ~~https://github.com/ManageIQ/manageiq-api-common/pull/129~~, https://github.com/ManageIQ/sources-api/pull/115
> Add test for Authentication patch with extra attributes

- config/routes.rb
- public/doc/openapi-3-v1.0.0.json
PATCH was missing for /applications.  Cost needs this to be able to set source status
> adding patch for applications

- lib/tasks/client_generate.rake
- public/doc/openapi-3-v1.0.0.json
**Issue**: ManageIQ/topological_inventory-ingress_api#71
* and added QuerySortBy to openapi.json
> Update of OpenApi Generator to 4.2.1

- Gemfile
- app/controllers/api/v1/sources_controller.rb
- spec/requests/api/v1.0/sources_spec.rb
Now triggering application availability checks with the source check_availability action.
> Adding support for application availability checks

- db/seeds/source_types.rb
@gtanzillo 
This PR exposes Satellite source type in UI.
Not sure which values we need to collect, which are required, validators, etc.
> Expose Satellite as source type in UI

- db/seeds/source_types.yml
This typo caused not-rendering of these inputs in UI
cc @dccurtis
> Fix yml for Amazon ARN authentication

- Gemfile
Fixes https://github.com/RedHatInsights/sources-api/issues/148
> Upgrading puma gem to 3.12.2 to fix Hakiri warning

- db/seeds/source_types.yml
- added/updated URLs to chrome static assets
> Update source types static icon assets url.

- Gemfile
Should resolve the logging errors we're seeing
> Set manageiq-loggers to a minimum of 0.4.2

- config/puma.rb
- lib/sources/api/events.rb
- lib/sources/api/messaging.rb
A single puma thread seems to be the only case where everything was working properly
> Go back to a single puma thread

- app/controllers/api/v1/sources_controller.rb
- lib/sources/api/messaging.rb
Don't use the same kafka connection for different topics
> Cache the kafka connection per-topic

- app/controllers/api/v1/sources_controller.rb
- config/puma.rb
- lib/sources/api/events.rb
- lib/sources/api/messaging.rb
- spec/controllers/api/v1x0/endpoints_controller_spec.rb
- spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
This is a cherry-pick of
https://github.com/RedHatInsights/sources-api/pull/162 - with conflicts resolved
https://github.com/RedHatInsights/sources-api/pull/163 - clean
> Cherry pick kafka fixes

- Gemfile
Same as https://github.com/RedHatInsights/topological_inventory-api/pull/276
> Upgrade to puma v4

- app/controllers/status_controller.rb
- config/routes.rb
- spec/swagger_spec.rb
TPINVTRY-827
Health check endpoint for OpenShift Liveness Probe
---
> [WIP] StatusController for Liveness Probe

- db/seeds/source_types.yml
Part of https://projects.engineering.redhat.com/browse/TPINVTRY-832
> Fix typos in source types fields

- app/controllers/api/v1/sources_controller.rb
- Setting both open and read timeout to 10 seconds.
> Added a timeout to the application availability checks performed.

- db/seeds/application_types.yml
> Rename Find It Fix It to Remediations

- lib/tasks/client_generate.rake
rake `client:generate` now updates `SourcesApiClient::VERSION` regarding to latest API version (with patch version always 0)
---
TPINVTRY-885
> Client generator: updating gem version

- Gemfile
https://hakiri.io/github/RedHatInsights/sources-api/master/34ceb213a3463ce75c8a1aca120803d0618040c2/warnings?name=Cross-Site+Scripting
> Bump puma to 4.3.3 for a Cross-Site Scripting Flaw

- app/controllers/api/v2x0/application_authentications_controller.rb
- app/models/application.rb
- app/models/application_authentication.rb
- app/models/authentication.rb
- config/routes.rb
- db/migrate/20200217181820_add_application_authentications.rb
- public/doc/openapi-3-v2.0.json
- spec/requests/api/v2.0/application_authentications_spec.rb
- spec/requests/api/v2.0/applications_spec.rb
This is needed to resolve a couple of issues:
https://github.com/RedHatInsights/sources-api/issues/183
https://github.com/RedHatInsights/sources-api/issues/182
which revolve around not having a direct link between an application and an authentication.
> Add an application-authentication join table

- app/controllers/api/v1/sources_controller.rb
https://projects.engineering.redhat.com/browse/TPINVTRY-839
> Add some additional logging when an availability check is requested

- Gemfile
- app/controllers/application_controller.rb
> Enabling filtering by association attribute for the REST API.

- app/models/application_authentication.rb
- public/doc/openapi-3-v2.0.json
- public/doc/openapi-3-v3.0.json
https://projects.engineering.redhat.com/browse/TPINVTRY-923
The ApplicationAuthentication class was causing duplicate
operation ID to be generated
https://github.com/RedHatInsights/insights-api-common-rails/pull/182
> Provide list_operation_id to resolve duplicates

- .travis.yml
- .travis_scripts/openapi-validator.sh
Apply the same change as RedHatInsights/approval-api#338
> Add openapi spec validation in travis

- db/migrate/20200527135242_add_last_checked_at_and_last_available_at_to_source.rb
- public/doc/openapi-3-v3.0.json
**Issue** #206 
Adding last_checked_at and last_available_at to Sources/Endpoints/Authentications/Applications
---
[**TPINVTRY-944**](https://projects.engineering.redhat.com/browse/TPINVTRY-944)
> Availability status timestamps migration

- Gemfile
Following version from https://github.com/RedHatInsights/topological_inventory-api/blob/master/Gemfile#L16
> Update puma versioning resolve Hakiri warnings

- app/models/application.rb
- spec/models/application_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/application_authentications_spec.rb
- spec/requests/api/v2.0/applications_spec.rb
- spec/requests/api/v2.0/sources_spec.rb
- spec/requests/api/v3.0/application_authentications_spec.rb
- spec/requests/api/v3.0/applications_spec.rb
- spec/requests/api/v3.0/sources_spec.rb
Validate source compatibility when creating Application.
> Application check

- app/controllers/application_controller.rb
Seeing a 401 error coming from Ansible Playbooks PATCH request need some extra logging.
> Debugging Playbook 401 error

- config/initializers/availability_status_listener.rb
- lib/availability_status_listener.rb
- spec/lib/availability_status_listener_spec.rb
https://projects.engineering.redhat.com/browse/TPINVTRY-970
> Add availability_status_listener subscribing to Kafka

- .travis.yml
Mistakingly left my branch name in the download URL
> Update openapi-validator.sh URL

- db/seeds/source_types.yml
part of https://projects.engineering.redhat.com/browse/TPINVTRY-1067
@syncrou
> Remove configure from endpoint titles

- db/seeds/source_types.yml
part of https://projects.engineering.redhat.com/browse/TPINVTRY-1067
@syncrou @gmcculloug @beccaglass
> Rename Ansible Tower to Red Hat Ansible Automation Platform

- db/seeds/source_types.yml
closes https://projects.engineering.redhat.com/browse/TPINVTRY-1065?filter=37613
**MERGE TOGETHER WITH RedHatInsights/sources-api#254**
cc @dccurtis
> Rename billing_source.bucket to billing_source.data_source.bucket

- db/seeds/source_types.yml
Please see https://issues.redhat.com/browse/TPINVTRY-1090
> Rename ARN to Cost Management ARN

- spec/swagger_spec.rb
to account for changes made in: https://github.com/RedHatInsights/insights-api-common-rails/pull/173
> Updated swagger_spec.rb

- config/initializers/prometheus_exporter.rb
**Issue** https://github.com/RedHatInsights/topological_inventory-api/issues/320
Fixing #264
> Fixed check for missing metrics port

- .codeclimate.yml
- Gemfile
[RHCLOUD-10237](https://issues.redhat.com/browse/RHCLOUD-10237)
> Rubocop update to 1.0.0

- .gitignore
- grafana-dashboards/README.md
- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Dashboard for Sources API/Monitor jobs
---
> Sources Grafana Dashboard

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Dashboard for Sources API/Monitor jobs
---
> Sources API Dashboard change 3

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Dashboard for Sources API/Monitor jobs
---
> Sources API Dashboard change 4

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Stage cluster was moved and prometheus datasource changed from crc-stg-01 -> ctcs02ue1
> Grafana dashboards: New stage cluster

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Datasource and namespace variables for RDS (db) graphs
---
> Grafana Dashboard: RDS variables

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Following #290 - graphs for RDS
---
> Grafana RDS graphs

- db/migrate/20201117165505_add_extra_to_applications.rb
- public/doc/openapi-3-v1.0.json
- public/doc/openapi-3-v2.0.json
- public/doc/openapi-3-v3.0.json
https://issues.redhat.com/browse/RHCLOUD-10745
Just adding the `:extra` column to `Applications`.
cc @syncrou @slemrmartin
> Add 'extra' jsonb column to Applications

- app/models/authentication.rb
- app/models/source.rb
- config/routes.rb
- db/migrate/20201120163548_add_source_to_authentications.rb
- public/doc/openapi-3-v1.0.json
- public/doc/openapi-3-v2.0.json
- public/doc/openapi-3-v3.0.json
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v2.0/authentications_spec.rb
- spec/requests/api/v3.0/authentications_spec.rb
https://issues.redhat.com/browse/RHCLOUD-10074
Adding a relationship between authentications and sources:
Source has_many Authentications
EDIT: also added `/sources/:id/authentications` endpoint per request from @rvsia
> Add `source_id` to Authentications and Source has_many relationship

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
> Grafana dashboards update

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Added thresholds and alert descriptions
---
[RHCLOUD-9951](https://issues.redhat.com/browse/RHCLOUD-9951)
> Grafana dashboard: Alerts

- db/seeds/application_types.yml
https://issues.redhat.com/browse/RHCLOUD-12001
> Rename SubWatch app to RHEL management

- app/models/authentication.rb
- app/models/super_key_meta_data.rb
- config/initializers/inflections.rb
- db/seeds/app_metadata.yml
- db/seeds/superkey_metadata.yml
- lib/sources/api/messaging.rb
This PR contains the schema changes I did when creating the initial superkey worker: https://github.com/lindgrenj6/sources-superkey-worker/
Basically I just added a few fields to the app meta data, and changed the schema a bit on the superkey metadata. I also added a helper method for producing a request to the superkey worker. 
I am continuing the work in #314, which uses said method and app meta data fields.
> updates to work with superkey worker

- app/models/concerns/seeding_concern.rb
> Deleting skipped source types/app types

- app/models/authentication.rb
- spec/models/authentication_spec.rb
https://issues.redhat.com/browse/RHCLOUD-12732
cc @rvsia
> only check for a single superkey if the authentication is a new record

- public/doc/openapi-3-v3.1.json
Zvika found this this morning, I forgot to include it in the OpenAPI spec for the bulk create payload.
> Add 'app_creation_workflow' to /bulk_create 'sources' payload

- Gemfile
- config/initializers/clowder_config.rb
- deploy/clowdapp.yaml
- docker-assets/entrypoint
- lib/sources/api/clowder_config.rb
Following #315 
---
[RHCLOUD-12241](https://issues.redhat.com/browse/RHCLOUD-12241)
> Clowder gem rename and ephemeral secrets

- Gemfile
---
[RHCLOUD-12241](https://issues.redhat.com/browse/RHCLOUD-12241)
> Clowder-common-ruby from rubygems

- db/seeds/superkey_metadata.yml
superkey work being done here: https://github.com/RedHatInsights/sources-superkey-worker/pull/13
> Add Cost and Usage Reporting for SuperKey

- docker-assets/entrypoint
- lib/sources/api/clowder_config.rb
Tmp output to get info, what's in the `rdsCa` and `sslMode` in the cdappconfig.json
> Tmp for stage certificate fix

- docker-assets/entrypoint
Following #356 to know exact format of the certificate in the file
> Tmp for stage certificate 2

- docker-assets/entrypoint
Following #357. RDS Certificate parsed by AWK seems better. Still kept echo outputs for checking
> rds certificate parsed by awk

- docker-assets/entrypoint
> RDS Ca better parsing by AWS

- Dockerfile
- docker-assets/entrypoint
Following #361 (diagnostics PR)
> Output of certificate file

- docker-assets/entrypoint
> Better saving of rds cert

- docker-assets/entrypoint
> entrypoint fix

- db/seeds/app_metadata.yml
> Add AWS acc number for subwatch in stage/qa

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Regex fix
---
[RHCLOUD-13391](https://issues.redhat.com/browse/RHCLOUD-13391)
> Fix grafana dashboard: Sources Api UP

- deploy/clowdapp.yaml
Reverts #371 
This reverts commit 3f6be22cb7fa9f06945128b3a71756b6e6641aa3, reversing
changes made to d164207c340e957e0d104217efae8ae9b1054145.
> Revert "Merge pull request #371 from slemrmartin/add-clowdapp-labels"

- app/models/source.rb
- lib/sources/bulk_assembly.rb
- spec/requests/api/v3.1/bulk_create_spec.rb
https://issues.redhat.com/browse/RHCLOUD-12233
Pretty self-explanatory.
> Default to `in_progress` availability_status for Superkey Sources

- app/controllers/api/v1/sources_controller.rb
- app/models/application.rb
- app/models/authentication.rb
- app/models/concerns/availability_status_concern.rb
- app/models/endpoint.rb
- app/models/source.rb
- deploy/clowdapp.yaml
- spec/factories.rb
- spec/models/application_spec.rb
- spec/models/authentication_spec.rb
- spec/models/endpoint_spec.rb
- spec/models/shared/availability_status.rb
- spec/models/source_spec.rb
Any changes to kafka messages to `platform.sources.event-stream` are not a subject of this PR..
---
**Issue** #317 
[RHCLOUD-13475](https://issues.redhat.com/browse/RHCLOUD-13475)
> Availability check refactoring + authentications status reset

- app/models/application.rb
Forgot to allow `Application` to be allowed "in progress", this is necessary for Cost to post in the status to us. 
cc @syncrou @dccurtis
> add in_progress to availability_status enum for Application model

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
added Up/Restarts/Errors and Satellite Operations panel from Topo
Also updated the Kafka lag Alert threshold line
---
[RHCLOUD-13848](https://issues.redhat.com/browse/RHCLOUD-13848)
> Grafana with SuperKey and Satellite metrics

- app/controllers/api/v1/applications_controller.rb
- app/controllers/api/v3x1/bulk_create_controller.rb
- app/models/concerns/event_concern.rb
- lib/sources/bulk_assembly.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/lib/availability_status_listener_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/applications_spec.rb
- spec/requests/api/v2.0/authentications_spec.rb
- spec/requests/api/v2.0/endpoints_spec.rb
- spec/requests/api/v3.1/bulk_create_spec.rb
https://issues.redhat.com/browse/RHCLOUD-12199
Creating the new `SourcesInstance.operation` messages, name subject to change. They will be raise on bulk_create events as well as update/~deletions~.
I will do delete in a follow-up PR.
> Add Records.(create|update) messaging

- deploy/clowdapp.yaml
- docker-assets/run_sidekiq
sidkiq needs the v2_key in order to decrypt records.
> update sidekiq worker to use v2_key

- Gemfile
This reverts commit 244b1ea4acd901144f305e5a20f0f8556544a1be.
> Revert "Pin insights-api-common to 5.0.2"

- Gemfile
https://hakiri.io/technologies/puma/issues/9432c5d4679400
> Fix CVE-2021-29509

- app/controllers/api/v3x1/sources_controller.rb
- config/routes.rb
- public/doc/openapi-3-v3.1.json
- spec/requests/api/v3.1/sources_spec.rb
https://issues.redhat.com/browse/RHCLOUD-14352
**DEPENDS ON:**
cc @rvsia 
\# TODO:
> Add /sources/:id/(pause|unpause) endpoints for source + application pausing

- lib/availability_status_listener.rb
- spec/lib/availability_status_listener_spec.rb
So troubleshooting issues with cost + swatch I found that cloudigrade was not sending the x-rh-identity header (here: https://github.com/cloudigrade/cloudigrade/blob/13a91f0f7aaf811ba38e5ca54c6e005c19694796/cloudigrade/util/redhatcloud/sources.py#L256) so that was causing cost to not be happy.
This PR basically adds a check on that header - if it isn't there we'll log a NASTY error message and skip producing the message. 
This is probably the ideal solution - the client apps (e.g. swatch, catalog, us) will think the messages are missing, but we are going to have log messages saying they're missing a header. Open to discussion otherwise.
> Validate incoming `platform.sources.status` messages by requiring x-rh-identity header

- app/controllers/internal/v2x0.rb
- app/controllers/internal/v2x0/tenants_controller.rb
- app/models/tenant.rb
- config/routes.rb
- lib/sources/api/internal_docs.rb
- private/doc/openapi-3-v2.0.json
- spec/controllers/internal/v2x0/tenants_controller_spec.rb
- spec/swagger_spec.rb
GET /internal/v1.0/tenants is not paginated
In production, there is >13000 records which causes >2s request duration
---
[RHCLOUD-11708](https://issues.redhat.com/browse/RHCLOUD-11708)
> Internal API v2 - pagination

- lib/availability_status_listener.rb
- spec/lib/availability_status_listener_spec.rb
https://issues.redhat.com/browse/RHCLOUD-14523
As we add the `x-rh-sources-psk` header - we need to maintain backwards compatibility on the `platform.sources.status` queue event processor. 
This was a little tough to implement - since basically we need to allow `(x-rh-id | x-rh-sources-account-number)`. To maintain backwards compatibility - if the user passes in the account number but *NOT* the x-rh-id, we generate one and pass it on.
> Add support and backwards compatibility for x-rh-sources-psk on the availability status listener

- app/jobs/superkey_delete_job.rb
https://issues.redhat.com/browse/RHCLOUD-14731
Running into this on stage, the superkey credential doesn't exist the source cannot be deleted. This PR just adds a check to see if the superkey credential exists trying to teardown the superkey request.
> handle nil superkey credential when deleting a superkey source

- deploy/clowdapp.yaml
~Just using a pre-canned UUID for now - going to potentially change it to a non-generated one if I can follow up how to.~
Found out about the ability to generate strings with bonfire, nice. Just made it a randomly generated 16 character key.
> Add default PSK value for ephemeral environment + local environment

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Might have to redo this since the latest changes weren't up there already...ugh
> fix dash for clowderized-apps + add some new dashes

- public/doc/openapi-3-v3.1.json
- spec/requests/api/v3.1/sources_spec.rb
https://issues.redhat.com/browse/RHCLOUD-13397
> Make field Source#app_creation_workflow readonly

- deploy/clowdapp.yaml
- pr_check.sh
Deprecating `smoke_test` script in favor of `cji_smoke_test`
> Update PR check

- .gitignore
- Gemfile
- app/controllers/application_controller.rb
- deploy/clowdapp.yaml
- lib/proxy_handler.rb
- proxy_rules/default_rules.json
https://issues.redhat.com/browse/RHCLOUD-16123
\# TODO:
> Add a proxy so we can send requests to the go svc selectively

- deploy/clowdapp.yaml
A few small tests when validating sources-api-go on my local minikube + the proxy functionality.
> Small fixes for sources-api clowdapp

- db/seeds/source_types.yml
Small changes according to mockups: https://marvelapp.com/prototype/g3hijg7/screen/77360186
- tenant id moved to the last position
- added required validators
- `Username` changed to `App ID`
> Update Azure superkey credentials according to UX

- app/models/super_key_meta_data.rb
- db/migrate/20211018212220_add_source_type_to_meta_data.rb
- db/seeds/app_metadata.yml
- db/seeds/source_types.yml
- db/seeds/superkey_metadata.yml
- lib/sources/api/messaging.rb
- lib/sources/super_key.rb
Reverted the old work I did and just added the new authtype for the wizard + the URLs to serve for the button.
\# TODO:
> Changing Azure "SuperKey" to use a button rather than Superkey Worker

- db/seeds/source_types.yml
https://issues.redhat.com/browse/RHCLOUD-16490
@rvsia the icon_url would need to be added on your side right?
> Add IBM Source Type

- db/seeds/application_types.yml
- db/seeds/source_types.yml
Attempts to add Red Hat Marketplace as an application type and a source type.
[[RHCLOUD-17299]](https://issues.redhat.com/browse/RHCLOUD-17299)
> [RHCLOUD-17299] Add rh-marketplace application and source types

- app/controllers/api/v1/mixins/index_mixin.rb
- app/controllers/api/v1/mixins/show_mixin.rb
- app/controllers/api/v3x0/mixins/index_mixin.rb
- app/controllers/application_controller.rb
- app/policies/app_meta_data_policy.rb
- app/policies/application_policy.rb
- app/policies/application_type_policy.rb
- app/policies/authentication_policy.rb
- app/policies/default_policy.rb
- app/policies/mixins/write_policy_mixin.rb
- app/policies/source_type_policy.rb
- app/policies/tenant_policy.rb
Just reverting all this stuff on the API side since this is giving us grief on prod. Will implement the specific changes on the Go side that the satellite team wants.
> Pull out system-specific logic from pundit checks

- lib/proxy_handler.rb
This should do the trick to proxy all requests over to the Go rewrite at will.
> Add switch to proxy _all_ requests to the rewrite

- Dockerfile
- app/models/authentication.rb
- db/migrate/20220405162144_migrate_auths_for_go.rb
- lib/go_encryption.rb
> Duplicate Encrypted Column for Go rewrite

- db/migrate/20220405162144_migrate_auths_for_go.rb
I'm already looking where password is not nil or not "" but maybe there are some in the db with empty strings.
> change go password_hash migration to check for empty string (blank) passwords
