- config/routes.rb
- spec/requests/api/v0_redirect_spec.rb
This changes the redirect code from 301 to 302 and fixes an issue
where /openapi.json would redirect to /openapi
Requires https://github.com/ManageIQ/manageiq-api-common/pull/50
> Use the routing helper from api common for major version redirects

- app/controllers/application_controller.rb
- spec/requests/api/v1.0/sources_spec.rb
Fixes https://projects.engineering.redhat.com/browse/TPINVTRY-222
Add support to generically handle ActiveRecord::NotNullViolation exceptions and return a proper error message instead of the 500 internal error.
Massage the exception message to get the following example:
{
"errors": [
{
"status": 400,
"detail": "Missing parameter - null value in column \"name\" violates not-null constraint"
}
]
}
> Add support to generically handle ActiveRecord::NotNullViolation exception

- app/controllers/application_controller.rb
- app/models/source.rb
- spec/requests/api/v1.0/sources_spec.rb
This fixes: https://projects.engineering.redhat.com/browse/TPINVTRY-223
Added model validator to assure that name is specified and is non-blank,
added rescue for ActiveRecord::RecordInvalid and appropriate spec for the empty name scenario.
> Assures that name specified is specified and not blank

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
Response signatures like:
"content": {
"application/json": {
"schema": {
"type": "object",
"items": {
"$ref": "#/components/schemas/Source"
}
}
}
}
Should just be for simple json objects and not arrays:
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/Source"
}
}
}
> Fix for POST create openapi JSON signatures

- lib/sources/api/events.rb
I'd like to have a way to disable kafka communication to simplify local setup.
What is the best way to do it? Something under `config/environment*`? Or an environment variable like in this PR? Or combination?
> Disable Kafka using an environment variable.

- lib/tasks/client_generate.rake
```
Sources API Version: 1.0
rake aborted!
NameError: uninitialized constant Net
/home/agrare/src/topological_inventory/sources-api/lib/tasks/client_generate.rake:30:in `generator_cli_jar'
/home/agrare/src/topological_inventory/sources-api/lib/tasks/client_generate.rake:57:in `generate_client'
/home/agrare/src/topological_inventory/sources-api/lib/tasks/client_generate.rake:74:in `block (2 levels) in <top (required)>'
/home/agrare/.gem/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => client:generate
(See full trace by running task with --trace)
```
> Fix Net undefined exception when generating client

- app/controllers/api/v1/sources_controller.rb
- app/controllers/application_controller.rb
- spec/requests/api/v1.0/sources_spec.rb
For sync between Cloudforms and Sources I need create Source with first payload. 
It means I'll provide UID from CF: `ExtManagementSystem.guid`. 
So I need to create Source with given uid.
> Create Source with given uid

- Gemfile
- app/controllers/api/v1/authentications_controller.rb
- app/controllers/api/v1/endpoints_controller.rb
- app/controllers/api/v1/mixins/destroy_mixin.rb
- app/controllers/api/v1/mixins/update_mixin.rb
- app/controllers/api/v1/source_types_controller.rb
- app/controllers/api/v1/sources_controller.rb
- app/controllers/application_controller.rb
- lib/sources/api/events.rb
When we raise an even on sources crud operations add the
current_forwardable headers to the event headers so that dependent
services know e.g. the tenant/request id that led to the change.
Depends on: ~~https://github.com/ManageIQ/manageiq-messaging/pull/46~~
> Add in the x-rh-identity headers to the event

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
openapi validator needs ID regexp pattern without "/" at the start and at the end.
cc @abellotti
> Changed openapi ID regexp pattern according to validator

- Gemfile
- app/controllers/api/graphql_controller.rb
- app/controllers/application_controller.rb
- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
Create/update requests are validated against openapi.json schema for parameter format. 
It checks only existing properties, unknown properties are checked yet.
---
* **Issue**: https://github.com/ManageIQ/manageiq-api-common/issues/67
> POST/PATCH validations against openapi.json

- app/controllers/api/v1x0.rb
- app/controllers/application_controller.rb
- lib/api/docs.rb
- spec/support/json_schema_matcher.rb
- spec/swagger_spec.rb
Occasionally we get an error about missing constant ManageIQ::Api::Docs
which should be actually be finding ::Api::Docs in lib/api/docs.rb in the
apps, but for some reason that isn't loaded yet.  Instead, move all of this
logic to manageiq-api-common and create
::ManageIQ::API::Common::OpenApi::Docs.instance
> [DEPENDS ON https://github.com/ManageIQ/manageiq-api-common/pull/82] Fix constant problems

- README.md
- config/database.dev.yml
With less than ruby 2.4 you get the following error:
```
NoMethodError (undefined method `named_captures' for #<MatchData:0x00007ff9a3ad4928>):
app/controllers/application_controller.rb:205:in `request_path_parts'
app/controllers/application_controller.rb:209:in `subcollection?'
app/controllers/api/v1/mixins/index_mixin.rb:24:in `raise_unless_primary_instance_exists'
app/controllers/api/v1/mixins/index_mixin.rb:6:in `index'
app/controllers/application_controller.rb:51:in `block (2 levels) in with_current_request'
app/controllers/application_controller.rb:51:in `block in with_current_request'
app/controllers/application_controller.rb:46:in `with_current_request'
```
> Update README stating dependency on ruby 2.4

- app/models/source.rb
- spec/requests/api/v1.0/sources_spec.rb
Ensure that the name of a source is unique within the tenant while
allowing duplicate names across tenants.
If a duplicate name is provided the error returned will be 400 and the
error doc will say:
Invalid parameter - Validation failed: Name has already been taken
Fixes https://projects.engineering.redhat.com/browse/TPINVTRY-284
> Validate source name is uniqueness within tenant

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
The openapi generator wasn't handling properly if attributes were
required.  This will mark an attribute as required if it isn't in the
set of read-only classes/attributes and if it is not-nullable and
doesn't have a db level default.
> Add handling of required properties

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
- spec/support/tenant_identity.rb
This change will enforce entitlements if the "entitlements" key is present in the x-rh-identity header.
If the "entitlements" key is present, the user must be entitled for either "insights" or "hybrid_cloud". I neither is entitled a 403 response is returned
Copied from https://github.com/ManageIQ/topological_inventory-api/pull/189
> Entitlement enforcement

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
- Moving the GraphQL Response into a separate schema definition as the client generator was getting confused with the inline response definition.
> Updated the openapi generator to use the new graphql description

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
Objects don't have required attribute similar to how endpoints are.
This causes invalid swagger specs.  Introduced by https://github.com/ManageIQ/sources-api/pull/44
> Undo required attributes for objects

- db/seeds.rb
Add the following new source types which will be uploaded from
cloudforms:
* VMware vSphere
* Red Hat Virtualization
* Red Hat OpenStack
* Red Hat Cloudforms
These cannot be added through the UI so no create parameters are
provided.
> Add source types from cloudforms

- app/models/concerns/tenancy_concern.rb
- public/doc/openapi-3-v1.0.0.json
- spec/requests/api/graphql_controller_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
Tenant (in this case account number) is necessary in API responses because apps and services subscribing to source
activity messages on kafka need a way to associate them with the specific account making the change.
https://projects.engineering.redhat.com/browse/TPINVTRY-416
> Reinstating tenant in API responses

- db/seeds.rb
Make user name fields in the json schema, used by the Sources UI to be consistent for AWS and Ansible sources.
Changing both to `username` to match the column name in the authentications table. This change will automatically update existing, seeded schema, when sources-api pod starts
https://projects.engineering.redhat.com/browse/TPINVTRY-533
/cc @rvsia
> Normalize user name fields in json schema

- app/models/endpoint.rb
- app/models/source.rb
We were missing the dependent destroy on the sources -> endpoints ->
authentications associations.  This was causing orphaned Authentication
records because the polymorphic authentication relationship couldn't do
a foreign key triggered cascade delete.
> Fix missing dependent destroy from sources

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
Fix to the openapi generate rake task and openapi spec so that the collection metadata includes the offset and limit.
Fix for TPINVTRY-569
> Fix to the openapi spec to update the CollectionMetadata to include offset and limit

- lib/tasks/openapi_generate.rake
Now that we've added tenant back to the API we need to also include the
tenant_id in the generator
> Add back tenant to openapi schema

- config/routes.rb
- public/doc/openapi-3-v1.0.0.json
Simplify the work of getting the list of application_types that a source
is enabled for by allowing a caller to go directly to the
application_types through applications.
```
curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEyMzQ1In19" http://localhost:3000/api/v1.0/sources/1/application_types 2>/dev/null | python -m json.tool
{
"data": [
{
"created_at": "2019-08-21T12:42:18Z",
"display_name": "Catalog",
"id": "1",
"name": "/insights/platform/catalog",
"updated_at": "2019-08-21T12:42:18Z"
}
],
"links": {
"first": "/api/v1.0/sources/1/application_types?offset=0",
"last": "/api/v1.0/sources/1/application_types?offset=0"
},
"meta": {
"count": 1,
"limit": 100,
"offset": 0
}
}
```
Fixes https://projects.engineering.redhat.com/browse/TPINVTRY-218
> Add an API to list application_types per source

- db/migrate/20190823150955_add_dependent_applications_to_application_types.rb
- db/seeds.rb
Add a list of dependent application type names to an application_type, and mark that catalog depends on topological-inventory.
This can be used by the orchestrator to generically determine which sources to spin collectors up for by dynamically checking the authentication_types as opposed to the hard-coded list that we currently have.
> Add a dependent_applications to application_types

- db/migrate/20190823151426_add_supported_source_types_to_application_types.rb
- db/migrate/20190823201412_add_supported_authentication_types.rb
- db/seeds.rb
- public/doc/openapi-3-v1.0.0.json
Adds a list of supported source_types and for those source_types what authentication_type is supported for the different application_types
This can be used by the UI to dynamically determine what apps can be enabled for the different sources.
> Add supported_source_types and _authentication_types to application_type

- app/controllers/internal/v1/tenants_controller.rb
The `as_json` method in ManageIQ::Api::Common will be called with the correct prefixes from `render :json => ...`
> Remove unnecessary call to :as_json

- lib/tasks/client_generate.rake
The 4.1.1 version of openapi-generator-cli was released and we're a few
versions behind.
> Update openapi-generator-cli version to 4.1.1

- db/seeds/source_types.rb
Renames form fields in DDF to allow better handling in UI.
@Ladas Is the  `authentication.extra.azure.tenant_id` the right endpoint (authentication) ?
Merge together with Sources-UI (https://github.com/ManageIQ/sources-ui/pull/94), and after frontend-components-sources (https://github.com/RedHatInsights/frontend-components/pull/132)
> Rename fields in DDF form schemas

- db/seeds/source_types.rb
- Adds an URL validator for URL fields
Accepts all kinds of address (ipv4, ipv6, with/out port, etc.), the only part which is required is protocol identifier. 
@gtanzillo Which protocols are we going to support? Right now, it is set to accept only `http`,`https`, but anything else could be added. Or we could make the protocol optional too.
> Add URL validator to DDF schemas

- docker-assets/run_rails_server
Fix a caching issue when running db:migrate and db:seed from the same
rake invocation
This was leading to:
```
rake db:migrate db:seed
...
ActiveModel::UnknownAttributeError: unknown attribute 'icon_url' for SourceType.
/opt/sources-api/db/seeds/source_types.rb:6:in `update_or_create'
/opt/sources-api/db/seeds/source_types.rb:22:in `<top (required)>'
/opt/sources-api/db/seeds.rb:2:in `block in <top (required)>'
/opt/sources-api/db/seeds.rb:2:in `each'
/opt/sources-api/db/seeds.rb:2:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:seed
```
> Don't run db:migrate and db:seed together

- db/migrate/20190919143736_add_receptor_node_id_to_endpoints.rb
- public/doc/openapi-3-v1.0.0.json
Add a receptor_node attribute for an endpoint to allow for tracking of
customer receptor nodes.  This will facilitate communication from
cloud.redhat.com through a c.r.c. controller to a customer's
environment.
> Add a endpoints.receptor_node attribute

- db/migrate/20190522195925_set_authentication_auth_type.rb
We need to use stubbed models when doing data migrations
> Don't use real models when doing a data migration

- lib/tasks/client_generate.rake
Source files for classes which get deleted are not automatically deleted
by the client generate and thus they are left around as garabge.
This cleans the target directories prior to running the openapi client
generator.
> Cleanup target client dir prior to generation

- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
ManageIQ/manageiq-api-common#93 allows empty bodies so these tests no
longer match the api-common expectations.
> Now empty bodies are allowed by the API

- db/seeds/application_types.rb
In application_types it is `ansible_tower`, in source types it is `ansible-tower`.
I changed it to `ansible_tower` in source-types. I am not sure what naming system are we going to use, but it makes sense to use the name with `_` as it is a standard Ruby syntax.
Do I need to write any migration? 
@gtanzillo @agrare
> Fix typo in application_types.db

- public/doc/openapi-3-v1.0.0.json
There was no return type defined for getDocumentation so generated
clients were not picking this endpoint up.
TPINVTRY-515
> Add return type to getDocumentation /openapi.json

- Gemfile
- public/doc/openapi-3-v1.0.0.json
Fixes TPINVTRY-639
Also pulls in v1.0.0 changes:
- Namespace dynamically defined GraphQL API version modules under ManageIQ::API::Common::GraphQL::Api #105
- New entitlements for Ansible and Migrations #113 and use them #115
- Forwarding of persona headers #109
- Extract GraphQLRequest to a schema object rather than inline #110
- Update to openapi_parser v0.5.0 #108
- Fixed errors around already defined constants in GraphQL #112
- Allow GraphQL generator to support paths with IDs like /primary/{primary_id}/ #107
- Constant problems related to GraphQL namespace #105
> Update manageiq-api-common dependency

- db/seeds/source_types.rb
closes https://github.com/ManageIQ/sources-api/issues/88
@agrare @gtanzillo 
**MERGE TOGETHER WITH UI PRs**: https://github.com/ManageIQ/sources-ui/pull/111
**Format**
```rb
schema = {
:authentication => [{
:type             => 'username_password', # same as in fields - authtype
:name             => 'Token', # Will be shown in the authentication selection step
:fields           => [
{:component => "text-field", :name => "authentication.authtype", :type => "hidden", :initialValue => "username_password"}
],
:additional_steps => [
]
}],
:endpoint       => {
:title  => 'Title', # If the endpoint will be on a separate step
:hidden => true, # If true, the endpoint step will be hidden, use if all components have `:hideField => true`
:fields => [
{:component => "checkbox", :name => …
```
> Split schemas

- db/seeds/source_types.rb
- Use `:hideField` instead of `:type => 'hidden'`
[hideField](https://data-driven-forms.org/renderer/component-api#commonpropsforallformfields)  is a way how to hide fields in a DDF forms.
`type: 'hidden'` still renders empty grid item => it creates empty spaces in the UI
`hideField` hides the field completely 
@agrare
> Use hideField in DDF schemas

- Gemfile
Sprockets 4.0 requires ruby 2.5 or higher:
https://travis-ci.org/ManageIQ/sources-api/jobs/596214534#L326
```
Installing sprockets 4.0.0
Gem::RuntimeRequirementNotMetError: sprockets requires Ruby version >= 2.5.0.
The current ruby version is 2.4.0.
An error occurred while installing sprockets (4.0.0), and Bundler
cannot continue.
```
> Lockdown sprockets to ~>3.0 to fix failure on 2.4

- db/seeds/application_types.rb
- db/seeds/source_types.rb
The Azure authentication_type was an access_key_secret_key type even
though the application_type specified username_password and azure also
includes a tenant_id field.
Introduce a new authentication_type to track the azure credential type.
Fixes https://github.com/ManageIQ/sources-api/issues/101
> Fix Azure authentication_type

- Gemfile
We need < 4.0 to pass on ruby 2.4 and we need >= 3.7.2 for an information disclosure issue
> Fix hakiri warning about sprockets

- .travis.yml
- Gemfile
Even limiting sprockets to what hakiri says are the patched versions didn't clear the security error, only bumping to sprockets 4.0 works.  To do this had to drop ruby 2.4 which sprockets 4.0 doesn't support and we don't use on our images anyway.
> Switch to sprockets 4.0 and drop ruby 2.4

- db/seeds/source_types.rb
- Adds ARN DDF schema for ARN for AWS/CM.
- basic structure and input fields
- Tags step is skipped until we get exact steps
`description` component is a component, where the content is added on the UI side, because it's a complex task to write these components into the schema without using Javascript syntax. (It uses bullet lists, copy clipboard components, etc.) However, if we decide that we want to store everything in the DB, it can be done, but it will take some time to come up with a good solution. (We could probably used some `md` parser... Client Side has advantages: it's simple and it can be easily localized.) 
~~_Waiting for completion of the UI implementation._~~
Work-in-progress: https://github.com/RedHatInsights/frontend-components/pull/212
> Add arn auth_type for aws+cm

- Gemfile
- app/controllers/application_controller.rb
Update to v2.0.1 of manageiq-api-common and fix the filter error
exception handling changed in https://github.com/ManageIQ/manageiq-api-common/pull/125
> Update to manageiq-api-common 2.0.1

- app/models/application.rb
- app/models/authentication.rb
- app/models/endpoint.rb
- db/migrate/20191028194041_add_availablility_status.rb
- public/doc/openapi-3-v1.0.0.json
Add AvailabilityStatus to Applications, Authentications, and Endpoints.
Extend the granularity of availability_status by allowing more resources
to contain availability status and an error message.
> Add AvailabilityStatus to Applications, Authentications, and Endpoints

- db/seeds/source_types.rb
Add a satellite source type for tracking on premise satellite
installations to track receptor endpoints.
> Add a Red Hat Satellite source-type

- db/seeds/source_types.rb
In the latest version of Final Form (which DDF is based upon) was fixed a bug, which we thought is a feature - re-initializing values when the component is rendered and now it does only for the first time. So, it wasn't possible to change these hidden values, when an user switches sourceTypes and authentication types - and the whole form fails because of that. 
So, we implemented our way how to do it by adding another prop `initializeOnMount` which does exactly what it was doing before.
**Links**
[DDF Documentation](https://data-driven-forms.org/renderer/initialize-mount)
[Final Form issue](https://github.com/final-form/final-form/pull/294)
> Use initializeOnMount for hidden fields

- Gemfile
Fixes a hakiri security warning about file access
> Update rack-cors to at least 1.0.4

- db/seeds/source_types.rb
- Adds a switch field with `Use Platform Receptor and PKI (?)`
- Adds a text input with Receptor ID sent to endpoint's endpoint as a `resource_node`
> Add receptor id field to Ansible Tower

- db/seeds/source_types.rb
related https://github.com/RedHatInsights/sources-ui/issues/127
Cost management needs the cluster id field to be shown in the review step.
//cc @rvsia
> Add cluster id to Openshift fields

- db/migrate/20191204145726_add_availability_check_url_to_application_types.rb
Add a URL for applications to register to allow for per-app availability
checking of sources.
This will be invoked by the normal availabililty check (scheduled and
on-demand) for all enabled applications for a source.
Applications will receive a POST action to check the availability of all
related resources for the specified source by ID, then the application
will update the source via the API to set the availability_status.
> Add an availability check URL for applications

- db/seeds/application_types.rb
This adds the find it fix it application type and adds satellite as the
only currently supported source type.
> Add the find it fix it application type

- app/controllers/api/v1/sources_controller.rb
- config/routes.rb
- lib/sources/api/events.rb
- lib/sources/api/messaging.rb
- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v1.0.0.json
- spec/controllers/api/v1x0/endpoints_controller_spec.rb
- spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
Adding the POST `/api/sources/:source_id/check_availability` action
- Action triggers an availability check on the Source[:source_id] specified
- Returns a 202 with empty {} body for now.
> Adding the POST /api/sources/:source_id/check_availability action

- lib/sources/api/events.rb
- spec/controllers/api/v1x0/endpoints_controller_spec.rb
- spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
This reverts commit 59a228bcb257f585608fe87b6f2a74b8a9613cff.
We started seeing issues with kafka events, it is possible that sharing this client connection is causing issues with writing to two different kafka topics
> Revert "Updated Sources::Api::Events to drop its messaging_client and use"

- db/seeds/source_types.rb
related to https://github.com/RedHatInsights/sources-ui/issues/128
Adding "Resource group", "Storage account" and "Subscription ID" fields.
//cc @nlcwong @dccurtis @rvsia
> Add Cost Management Azure fields to source_types

- app/controllers/api/v1/sources_controller.rb
- db/migrate/20191213165335_remove_availability_check_url_from_application_types.rb
- public/doc/openapi-3-v1.0.0.json
- spec/requests/api/v1.0/sources_spec.rb
Updated sources-api so that we don't store the availability_check_url in the application type, but leverage it from the environment.
this way applications can define their own for the different staged environments without needing to update the database.
> [WIP] Updated sources-api to leverage environment for availability_check_urls

- app/models/endpoint.rb
- spec/models/endpoint_spec.rb
Previously it was possible to have multiple "default" endpoints.  This
can cause issues when code assumes that only one endpoint is default.
> Ensure that only one endpoint is "default"

- app/controllers/api/v1/mixins/index_mixin.rb
- app/controllers/application_controller.rb
- spec/requests/api/v1.0/filter_spec.rb
Enabling the sort_by parameter, was only exposed via GraphQL for all, for rest, only the common dummy app in common had it exposed.
Added a small spec to verify it is now exposed here, the comprehensive tests for sort_by is in common.
Fixes: TPINVTRY-801
> Exposing the sort_by parameter for queries.

- db/seeds/source_types.yml
fixes TPINVTRY-711
Token (password) is required for Openshift
User name (username) and Secret key (password) are required for Ansible Tower
> Add missing required validators to Openshift and Ansible Tower

- app/controllers/api/v1/sources_controller.rb
- app/controllers/application_controller.rb
- config/puma.rb
To help investigate lockups in the sources-api drop to a single puma thread and log before and after publishing to kafka topics including the name of the topic.
This should help us identify if the source of the issue is concurrency related or using one kafka client to publish to multiple topics.
> Drop to a single puma thread and log before and after publishing to kafka

- db/seeds/source_types.yml
Typo in chrome has been fixed (https://github.com/RedHatInsights/insights-chrome/pull/547), so here we go
> Fix Azure icon typo

- config/puma.rb
- lib/sources/api/events.rb
- lib/sources/api/messaging.rb
- spec/controllers/api/v1x0/endpoints_controller_spec.rb
- spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
Cache the kafka connection per thread not globally and set the puma
threads back to 5
> Cache kafka connection per thread

- app/models/concerns/seeding_concern.rb
To help improve debugging of missing seeded records we can log
creates/updates/deletes for the seed classes.
> Add logging to the seeding step

- lib/sources/api/events.rb
- lib/sources/api/messaging.rb
- spec/controllers/api/v1x0/endpoints_controller_spec.rb
- spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
It seems that sharing a common kafka connection for posting to different
topics causes issues with being unable to assign partitions to messages
leading to Kafka::DeliverFailed errors
> Don't share a kafka connection

- app/controllers/api/v1/sources_controller.rb
- lib/sources/api/events.rb
- lib/sources/api/messaging.rb
- spec/controllers/api/v1x0/endpoints_controller_spec.rb
- spec/controllers/api/v1x0/mixins/destroy_mixin_spec.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
To prevent messages destined for non-existant topics blocking other valid messages from being delivered, check the list of topics (cached) before publishing a message.
> Check list of available topics before publishing a message

- config/puma.rb
Now that we have figured out what was blocking the kafka publish we
should be able to bump the puma threads back up to 5.
> Bump puma threads back up to 5

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/support/tenant_identity.rb
Only allow org-admin to be able to use the sources-api - All others get a 403.
For development environments, the following can be set to skip the check:
```
BYPASS_RBAC=true
```
> Only allow org-admin to be able to use the sources-api.

- app/controllers/api/v1/graphql_controller.rb
although grapqhl request is POST, it's actually like GET so RBAC read-only access should be allowed
> Allow read-only access for graphql

- spec/controllers/application_controller_spec.rb
The application controller was expecing the events to get
messaging_client but that changed recently.
> Fix the application controller events spec

- db/seeds/application_types.yml
- db/seeds/source_types.yml
This adds an application_type for CloudMeter and also adds a new
cloud-meter-arn auth type.  Since the ARN that cloud meter needs is
different from the one that cost management needs we need a different
auth-type for now.
Fixes https://github.com/RedHatInsights/sources-api/issues/172
> Add a Cloud Meter application and Auth Type

- db/seeds/source_types.yml
Sorry, my fault, I haven't noticed this during the review. :(
`stepKey` is only used when the authtype has custom UI position. And right now, Cloud Meter ARN is just a plain input.
> Remove stepKey from Cloud Meter ARN auth

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v2.0.json
- spec/requests/api/v2.0/sources_spec.rb
The tenant attribute maps to the user's identity.account_number which is only relevant internally.  Users of the API who login through 3scale will only ever be able to see a single tenant so this attribute isn't helpful and can be confusing.  Also since it isn't a proper relationship (it is the tenant.external_tenant not tenant_id) it can trip up things like filtering.  In v2.0 we should drop this attribute.
Relates to JIRA: TPINVTRY-742
> Don't return the 'tenant' attribute

- app/controllers/api/v1/sources_controller.rb
Satellite availabiliity check needs Source UID as an argument, so passing it in Sources API will save one API request from satellite-operations
> Source UUID to Kafka in Check availability

- db/seeds/application_types.yml
Since this value is displayed in the UI, we need to change it because the customer will expect to see the product name "Subscription Watch", not the sub-component name "Cloud Meter".
> change display name "Cloud Meter" to "Subscription Watch" to better match the public-facing product name

- Gemfile
- app/controllers/application_controller.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/sources_spec.rb
- spec/support/tenant_identity.rb
For the usecase of a satellite system auto registering itself we have to allow for machine credentials to post to sources.
Depends on: https://github.com/RedHatInsights/insights-api-common-rails/pull/162
Relates to JIRA: https://projects.engineering.redhat.com/browse/TPINVTRY-870
> Allow machine credentials to create sources

- app/controllers/api/v1/graphql_controller.rb
- spec/requests/api/graphql_controller_spec.rb
- spec/support/tenant_identity.rb
Fix a bug introduced by renaming request_is_readonly to request_is_readonly? (since it is a boolean method) [here](https://github.com/RedHatInsights/sources-api/pull/190/files#diff-55c5b7aecfb519d0e4880eaf2788eb6eL68) but this broke the graphql controller which overrides this to allow for posts to be treated as readonly.
Also add a spec test to cover this case.
> Fix bug with graphql posts with non-org-admin

- db/seeds/source_types.yml
TPINVTRY-877
Receptor ID won't be supported in GA
> Remove Receptor ID field from ansible Tower

- app/controllers/api/v1/sources_controller.rb
The satellite receptor connection needs the satellite instance id which is stored in the source.source_ref attribute.
> Send the source.source_ref for availability check

- app/controllers/api/v1/sources_controller.rb
Unifying log messages
Availability can be traced in Kibana by message `Source#availability_check <id>`
> Trackable Source#availability_check

- db/seeds/application_types.yml
As found on recent demo.  The application type should match the latest Catalog naming.
cc @sbuenafe-rh
> Rename Catalog to Automation Services Catalog

- db/seeds/source_types.yml
There are new source types icons mocked by UX
cc @syncrou
> Update source types logos according to UX

- db/migrate/20200422154616_rename_satellite_initial_value.rb
- db/seeds/source_types.yml
https://projects.engineering.redhat.com/browse/TPINVTRY-922
Simple PR to fix typo in the `db/seeds/source_types.yml` file as well as a migration to fix currently running instances of the Sources API.
> Fix typo in satellite source and add migration to fix currently running instances

- config/application.rb
- config/environments/production.rb
The environment variable is called RAILS_LOG_LEVEL with the valid values
- info
- debug
- error
- warn
> Support log_level coming from environment variable

- Gemfile
- app/controllers/application_controller.rb
- spec/requests/api/v1.0/application_types_spec.rb
- spec/requests/api/v1.0/authentications_spec.rb
- spec/requests/api/v1.0/endpoints_spec.rb
- spec/requests/api/v1.0/filter_spec.rb
- spec/requests/api/v1.0/source_types_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/application_authentications_spec.rb
- spec/requests/api/v2.0/application_types_spec.rb
- spec/requests/api/v2.0/applications_spec.rb
- spec/requests/api/v2.0/authentications_spec.rb
- spec/requests/api/v2.0/endpoints_spec.rb
- spec/requests/api/v2.0/filter_spec.rb
- spec/requests/api/v2.0/source_types_spec.rb
- spec/requests/api/v2.0/sources_spec.rb
- spec/requests/api/v3.0/application_authentications_spec.rb
- spec/requests/api/v3.0/application_types_spec.rb
- spec/requests/api/v3.0/applications_spec.rb
- spec/requests/api/v3.0/authentications_spec.rb
- spec/requests/api/v3.0/endpoints_spec.rb
- spec/requests/api/v3.0/filter_spec.rb
- spec/requests/api/v3.0/source_types_spec.rb
- spec/requests/api/v3.0/sources_spec.rb
This is needed to conform with the IPP which requires that error objects conform to the JSON API.
Uses the newer version of the common gem.
https://jsonapi.org/format/#errors
Which states that status is a string and not an integer.
https://projects.engineering.redhat.com/browse/TPINVTRY-925
> Support for status type of string

- db/seeds/source_types.yml
There is a new major DDF version which changes some strings. Please see https://data-driven-forms.org/migration-guide
- removes unnecessary `validator` naming from validator types
- `switch-field` to `switch`
Should be merged after 
The UI has fallbacks prepared.
> Update DDF strings to version 2

- db/seeds/source_types.yml
OpenShift logo contains a little bit different naming than the product name:
vs
`OpenShift Container Platform`
@syncrou This should be probably decided by the copy, but I am not sure who is it. :D 
Mocks
https://marvelapp.com/574481j
> Add 'Red Hat' to OpenShift product name, drop CloudForms

- Gemfile
- app/controllers/api/v1/applications_controller.rb
- app/controllers/api/v1/mixins/destroy_mixin.rb
- app/models/application.rb
- app/models/application_authentication.rb
- app/models/authentication.rb
- app/models/concerns/event_concern.rb
- app/models/endpoint.rb
- app/models/source.rb
- spec/requests/api/v3.0/application_authentications_spec.rb
- spec/requests/api/v3.0/applications_spec.rb
- spec/requests/api/v3.0/authentications_spec.rb
- spec/requests/api/v3.0/endpoints_spec.rb
- spec/requests/api/v3.0/sources_spec.rb
https://projects.engineering.redhat.com/browse/TPINVTRY-916
The logic of raising Kafka messages originally is defined in `application controller`'s destroy method (via `mixin`), so it will be missed even when `:dependent => :destroy` is set. This PR moved it into `after_destroy` callback, to guarantee message is sent out.
> Raise Kafka events when source and its associated applications are deleted

- app/controllers/application_controller.rb
Undo the log message changes from
PR #235 
PR #236 
Since it would be done cleanly by delegating it to the common gem.
> Removed debug log messages

- lib/tasks/openapi_generate.rake
- public/doc/openapi-3-v3.0.json
OpenAPI definitions: Add `readOnly` for authtype in Authentication
Based on https://projects.engineering.redhat.com/browse/TPINVTRY-932.
> Making authtype readonly(OpenAPI)

- app/models/endpoint.rb
- spec/models/endpoint_spec.rb
https://projects.engineering.redhat.com/browse/TPINVTRY-999
We are running into various issues where users create source/endpoint/authentication via API and if they do not pass in `default => true` in the POST /endpoints call, the source then doesn't know about an endpoint, which causes availability checks to show "Partially Available".
This way there is always a default endpoint for availability checking, even when created via the api.
> Set the first endpoint created on a source as default

- config/routes.rb
- public/doc/openapi-3-v1.0.json
- spec/requests/api/v1.0/source_types_spec.rb
This was found to be a bug on the stage environment, users of the v1.0 API were still able to create source types, which should not be allowed.
This change simply removes that route.
> Remove SourceType create operation from v1 of the API

- db/seeds/source_types.yml
fixes https://issues.redhat.com/browse/TPINVTRY-1075
`stepKey` attribute is used to append a field to a step in the wizard, however S3 Bucket is exclusive to the cost management application, so the step key should indicate it belongs to the app.
This should prevent this value appearing in the no app arn summary details.
> Remove S3 Bucket Name field from wizard summary

- db/seeds/source_types.yml
Closes https://issues.redhat.com/browse/TPINVTRY-1077
This is a draft PR for discussing how to properly solve this issue. (If it's going to be an issue at all.)
There are basically two options:
1) Remove unused source types from API (**this PR**)
2) Hide unused sources types in the UI
Personally, I would go with the first option as I am trying to make the UI as much consistent to the API as possible. Data should be controlled by the API, not in the UI that just shows them. Hiding them would introduce two additional issues: users won't see sources created from the API and there would have to be a list with hidden types (so more code to keep updated and more code with possible bugs). Also, it doesn't make much sense to have unusable types defined in the API.
What do you think @syncrou ?
cc …
> Remove unused source types

- db/migrate/20200911162327_move_endpoint_authentications_to_application_authentication.rb
This will make the availability check always fall back to the Application status, since no endpoint is available.
Tested locally and the fallback code works :+1:, now we just need the UI to create them under the application instead. This should probably go in after that UI change so we don't have to run this again.
JIRA: https://projects.engineering.redhat.com/browse/TPINVTRY-1082
\# TODO:
cc @syncrou @dccurtis
> Add Migration for Cost Sources to use Application Authentication resources

- docker-assets/run_rails_server
https://issues.redhat.com/browse/RHCLOUD-9736
Basically this PR is pulling out the `rake db:seed` step from the initialization of the rails server - moving it to an `initContainer` in the openshift template. This way the server doesn't take ages to start up. 
(also adding the `&&` to the commands so if a migration fails the whole thing fails)
**DEPENDS ON:**
> Skip running rake db:seed when running just the rails server

- Gemfile
- app/controllers/api/v1/applications_controller.rb
- app/controllers/api/v1/authentications_controller.rb
- app/controllers/api/v1/endpoints_controller.rb
- app/controllers/api/v1/graphql_controller.rb
- app/controllers/api/v1/mixins/destroy_mixin.rb
- app/controllers/api/v1/mixins/update_mixin.rb
- app/controllers/api/v1/source_types_controller.rb
- app/controllers/api/v1/sources_controller.rb
- app/controllers/api/v2x0/application_authentications_controller.rb
- app/controllers/api/v2x0/source_types_controller.rb
- app/controllers/application_controller.rb
- app/policies/application_authentication_policy.rb
- app/policies/application_policy.rb
- app/policies/authentication_policy.rb
- app/policies/default_policy.rb
- app/policies/endpoint_policy.rb
- app/policies/mixins/write_policy_mixin.rb
- app/policies/source_policy.rb
- config/application.rb
- config/initializers/custom_exception_mappings.rb
- spec/controllers/application_controller_spec.rb
Setting up some killer RBAC for Sources!
EDIT: Deciding to break this up so it's easier to review. 
This PR is for the first part of this ticket: https://issues.redhat.com/browse/RHCLOUD-9963
Basically all this PR is doing is moving everything over to pundit-based access checks. It is using the same `org_admin?` check as before basically but just going through pundit instead of doing it manually. 
\# TODO:
~- [ ] Add RBAC lib class~
~- [ ] Add ACL table to cache rbac results.~
> Move to Pundit Gem for authorization

- .codeclimate.yml
- .rubocop.yml
- .yamllint
Because of https://github.com/ManageIQ/guides/pull/443 rubocop rules were moved to another repo. 
So we are moving the file to our common repo.
---
[RHCLOUD-10237](https://issues.redhat.com/browse/RHCLOUD-10237)
> Update Rubocop rules to point at new api-common repo

- lib/sources/api/messaging.rb
Same change as on topo + ingress, memoizing the api client so we don't instantiate (and then never close) a bunch of messaging clients.
> Memoize `Sources::Api::Messaging.client` instead of using thread-local storage

- app/models/application.rb
- app/models/authentication.rb
After destroying of Application or Authentication, if ApplicationAuthentication relation exists, kafka event `ApplicationAuthentication.destroy` has to be raised as a cascade delete operation
---
[RHCLOUD-10263](https://issues.redhat.com/browse/RHCLOUD-10263)
> Publishing Kafka event ApplicationAuthentication.destroy

- app/policies/default_policy.rb
- lib/sources/rbac/access.rb
- spec/controllers/application_controller_spec.rb
- spec/lib/sources/rbac/access_spec.rb
- spec/requests/api/rbac_spec.rb
https://issues.redhat.com/browse/RHCLOUD-9964
Pretty self-explanatory, this just adds in the call out to the RBAC service for authorization when doing anything that requires write access (admin-only for now). 
The only permission as of right now is `sources:*:*` which we will potentially expand later.
> Add call out to RBAC for write-access check

- lib/sources/rbac/access.rb
I think this is the problem we're seeing, since it was a class var and it was memoized the first person who logged in sets the permissions for the rest of the hits. Not ideal.
> Remove memoization of rbac access class variable

- app/controllers/api/v1/sources_controller.rb
- lib/sources/api/messaging.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/sources_spec.rb
- spec/requests/api/v3.0/sources_spec.rb
https://issues.redhat.com/browse/RHCLOUD-10747
It seems we are running into this issue a lot where the message producers will "forget" that a topic exists, and proceed to not produce the availability status messages anymore, seemingly happens in random intervals but the logs are filled with messages like this:
```json
{
"@timestamp": "2020-11-16T16:04:31.059618 ",
"hostname": "sources-api-774b8d79cc-6m2zs",
"pid": 32,
"tid": "2afa089bbc0c",
"level": "err",
"message": "Not publishing message to non-existing topic: Source#availability_check [{\"source_id\"=>1307, \"topic\"=>\"platform.topological-inventory.operations-azure\"}]",
"request_id": "a240ffd873bc45fea2e6665e8b925552"
}
```
even though the topic definitely exists.
---
This PR is one possible solution - rather than checking if a …
> Remove check for whether a topic exists when checking Source#availability_status

- lib/availability_status_listener.rb
- spec/lib/availability_status_listener_spec.rb
Kafka availability_status_listener fix.
Based on: https://github.com/RedHatInsights/sources-api/issues/286
Depends on: [ ] https://github.com/RedHatInsights/topological_inventory-providers-common/pull/68
In the pictures bellow you can see the sources-api command line output containing DB update for all realted tables. 
services/ansible-tower-operations.sh :
sources-api:
DB:
EDIT: 
- Add missing message type for logging message. 
- example: Kafka message **availability_status** received with payload....
> Kafka availability_status_listener fix.

- app/models/application.rb
- app/models/authentication.rb
- app/models/concerns/availability_status_concern.rb
- app/models/endpoint.rb
- app/models/source.rb
- spec/models/application_spec.rb
- spec/models/authentication_spec.rb
- spec/models/endpoint_spec.rb
- spec/models/shared/availability_status.rb
- spec/models/source_spec.rb
Since we cannot be sure about the `availability_status` after attribute update, we are adding the availability_status concern, which removes `availability_status`, `availability_status_error` and `last_checked_at` attributes from `Sources`, `Applications`, `Endpoints` and `Authentications`.
This PR is based on https://issues.redhat.com/browse/RHCLOUD-10278.
> Add availability_status concern

- lib/availability_status_listener.rb
- spec/lib/availability_status_listener_spec.rb
The availability status listener wasn't passing on headers, this fixes that. 
\# DEPENDS ON:
> Pass on headers that come through the Availability Status Listener

- Gemfile
- app/controllers/application_controller.rb
- spec/requests/api/rbac_spec.rb
After adding `:extra` to the `Application` model it was reported by @dccurtis that patch-ing extra wasn't working.
Digging into it a bit resulted in having to switch to using the common gem's `params_for_update` method from the Parameters mixin. 
---
This change also exposed some problems in the common gem method as well, so there is a subsequent PR over there that will be linked here.
\# DEPENDS ON:
> Switch to using common gem's `params_for_update`

- db/migrate/20210121161913_move_arn_auth_to_username.rb
- db/seeds/source_types.yml
https://issues.redhat.com/browse/RHCLOUD-11834
cc @rvsia 
Backend migration for moving the arn/cloud-meter-arn authentications over to using username instead of password.
I left the data in the password for backward compatibility as well. 
---
EDIT: adding wait to merge so we can do this in sync with the UI.
> Migrate ARN Authentications from storing ARN in password -> username

- db/seeds/application_types.yml
- db/seeds/source_types.yml
Source Type and ApplicationType seeds for Google Cloud Engine
---
[RHCLOUD-11249](https://issues.redhat.com/browse/RHCLOUD-11249)
> Google Seeds

- app/models/app_meta_data.rb
- app/models/application_type.rb
- app/models/meta_data.rb
- app/models/super_key_meta_data.rb
- db/migrate/20210119201052_create_meta_data.rb
- db/seeds.rb
- db/seeds/app_metadata.yml
- db/seeds/superkey_metadata.yml
Heres the initial modeling for AppMetaData ~`AppMetaDatum` (latin anyone? since data is apparently plural)~. 
EDIT: ended up making MetaData a STI class. We now have 2 subclasses: `SuperKeyMetaData` and `AppMetaData`. They will both be seeded. 
- I set up a manual `seed` method on both since the seeding concern won't work for this type of stuff
- turns out you can embed `json` directly into `yaml`, so we can directly support the JSON payloads in the superkey seeding file. 
- there is an association on `ApplicationType` for both `*meta_data`'s for easy access
- the `name` enum is what defines what we do/do not support for SuperKeyMetaData, can expand as necessary (or the more we support)
- the `substitutions` column is what holds the key-value pairs of what should be substituted out of the …
> Add meta_data table + models + seeding

- app/controllers/api/v3x1.rb
- app/controllers/api/v3x1/app_meta_data_controller.rb
- config/initializers/inflections.rb
- config/routes.rb
- db/migrate/20210126142101_add_type_to_meta_data.rb
- public/doc/openapi-3-v3.1.json
- spec/factories.rb
- spec/requests/api/v3.1/app_meta_data_spec.rb
- spec/requests/api/v3.1/application_authentications_spec.rb
- spec/requests/api/v3.1/application_types_spec.rb
- spec/requests/api/v3.1/applications_spec.rb
- spec/requests/api/v3.1/authentications_spec.rb
- spec/requests/api/v3.1/endpoints_spec.rb
- spec/requests/api/v3.1/filter_spec.rb
- spec/requests/api/v3.1/graphql_controller_spec.rb
- spec/requests/api/v3.1/source_types_spec.rb
- spec/requests/api/v3.1/sources_spec.rb
- spec/swagger_spec.rb
PR for adding all the endpoints for `ApplicationType` `MetaData` models.
After thinking it through, we don't want these to be editable in any way (except maybe /internal, but they're gonna be public anyway), so I'm going to add some seeding for the app meta data type. 
\# TODO:
~- [x] post~
~- [x] patch~
~- [x] delete~
> Add app_meta_data endpoints

- app/models/source.rb
- db/migrate/20210125173413_add_app_creation_workflow_to_sources.rb
- public/doc/openapi-3-v3.1.json
https://issues.redhat.com/browse/RHCLOUD-11657
Adding this field to track what type of workflow we should use when creating applications off of said source. It's an enum (in the openapi and in the rails model validation) of `%w(trust semi-trust paranoid)`.
> Add 'app_creation_workflow' enumerated string to Source to track creation type

- app/models/concerns/seeding_concern.rb
This is so we can skip passing along google cloud to prod.
This will require the e2e-deploy PR to be merged as well as the app-interface deploy.yml updated to skip google-cloud source type. 
DEPENDS ON:
> Add support for skipping specified sourcetypes/applicationtypes

- app/models/concerns/seeding_concern.rb
This reverts commit b9fb81ccf8cf733a3e438a0abcfb65f72e199e6b, reversing
changes made to b61783c5aa55227f1e1e6e2f6a2618473c013c5e.
So basically this reversed my change, we call `.destroy` on each type _left in the hash_ at the end, here: https://github.com/RedHatInsights/sources-api/blob/3d1681a75646866e896297595fb50f9550da5817/app/models/concerns/seeding_concern.rb#L28-L29
By deleting it from the hash (this PR) it doesn't get cleaned up from the db. After removing that line in CI I get the successful deletion:
```
{"@timestamp":"2021-02-17T18:43:40.129493 ","hostname":"sources-api-1099-wr8lr","pid":148,"tid":"2b14697bd95c","level":"info","message":"Deleting google"}
```
> Revert "Merge pull request #320 from slemrmartin/seed-excluded-google"

- app/controllers/api/v1/sources_controller.rb
This was causing an error if Kafka had issues, this leg of the code
would get executed and fail.
```
{"@timestamp":"2021-02-18T19:19:27.584275 ","hostname":"sources-api-1104-8wpvz","pid":34,"tid":"2abee0fb98d8","level":"err","message":"NameError: undefined local variable or method `e' for #<Api::V1x0::SourcesController:0x0000557dc0bd2a20>\n/opt/sources-api/app/controllers/api/v1/sources_controller.rb:46:in `rescue in check_availability'\n/opt/sources-api/app/controllers/api/v1/sources_controller.rb:29:in `check_availability'\n/usr/share/gems/gems/actionpack-5.2.4.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\n/usr/share/gems/gems/actionpack-5.2.4.5/lib/abstract_controller/base.rb:194:in `process_action'\n/usr/share/gems/gems/actionpack-5.2.4.5/lib/action_control …
```
> Missing => in rescue

- app/controllers/api/v3x1/bulk_create_controller.rb
- spec/requests/api/v3.1/bulk_create_spec.rb
cc @mkanoor
I forgot to include the `#{model}.create` when creating via /bulk_create. This fixes that! Whoops!!
> raise create events when resources are created via /bulk-create

- app/models/application.rb
- app/models/authentication.rb
- app/models/source.rb
- app/models/source_type.rb
- lib/sources/bulk_assembly.rb
- lib/sources/super_key.rb
- spec/models/authentication_spec.rb
As found in the initial integration by @rvsia and mentioned after merge in #314, instead of setting `:authtype => "superkey"` in the payload it will be better to look up the sourcetype[:authentication] hash and find out which authentication type is the superkey type.
\# TODO:
> Lookup the SuperKey authtype rather than assuming it is just "superkey"

- lib/sources/api/messaging.rb
Forgot to update this service class with the new method name, need this for teardown to work properly.
> fix missed method call name in superkey service class

- db/migrate/20210224151150_remove_status_from_authentication.rb
- public/doc/openapi-3-v1.0.json
- public/doc/openapi-3-v2.0.json
- public/doc/openapi-3-v3.0.json
- public/doc/openapi-3-v3.1.json
Adding migration for removing `status` and `status_details` columns from `authentications` table. 
```
remove_column :authentications, :status,         :string
remove_column :authentications, :status_details, :string
```
Based on https://github.com/RedHatInsights/sources-api/issues/317
Edit: removing the `status` and `status_details` instead of the `availability_status` related attributes based on the @lindgrenj6 and @rvsia comments.
> Removing status from authentication model

- spec/controllers/application_controller_spec.rb
This spec has been skipped with `xit` since I added rbac support, the logic doesn't quite work with the new rbac-lite workflow, so this PR is jsut removing it.
> remove skipped org_admin spec based on old behavior

- deploy/clowdapp.yaml
- docker-assets/entrypoint
Makes db pool size configurable by ENV. Defaults to 5 (current value)
---
[RHCLOUD-12757](https://issues.redhat.com/browse/RHCLOUD-12757)
> Configurable DB Pool size

- app/models/concerns/availability_status_concern.rb
So in debugging why the superkey worker wasn't able to PATCH the availability status back to the Application + Source objects (it was just always nil), I found out that if the changeset includes availability status AND anything else, it removes said settings. 
This is a problem for SuperKey worker because we patch back metadata to store in the `:extra` column. So here I added the superkey_data to the payload in order for the patch to work. 
---
This does bring up a bigger discussion though - should we change this logic to the opposite, e.g. "if any of these fields change -> nuke the status" rather than ignoring certain fields and updating if anything ELSE is included.
> Add `superkey_data` field to ignore list

- db/migrate/20210308170013_link_authentications_to_sources.rb
https://issues.redhat.com/browse/RHCLOUD-12814
A user realized there could be instances where `Authentication#source_id` is unset due to us not running a migration when we initially added the `source_id` column to Authentications.
Note this does not fix the fact that there DEFINITELY are dangling authentications out there - e.g. in CI there are like 200+ that are pointing to an endpoint/application that just doesn't exist.
> Migrate so any dangling Authentications with source_id unset get set

- db/seeds/app_metadata.yml
Adding the actual account numbers for CI in the AppMetaData seed yml file. 
This way superkey will finally work, it's working right now all except the role creation (due to the bad account number).
> Add SuperKey account numbers to app_meta_data seed

- app/controllers/api/v3x1/bulk_create_controller.rb
- spec/requests/api/v3.1/bulk_create_spec.rb
2 bugs here:
https://issues.redhat.com/browse/RHCLOUD-12783
https://issues.redhat.com/browse/RHCLOUD-12870
cc @zsadeh 
Forgot to raise the event for the `ApplicationAuthentication` resources created during bulk_create, which was making it so superkey resources for subscription watch weren't getting registered.
This fixes that.
> raise event for ApplicationAuthentication resources created

- Gemfile
- deploy/clowdapp.yaml
- docker-assets/entrypoint
- lib/sources/api/clowder_config.rb
ClowdApp name (and oc app name) will be equal to the name of the repo
url sources-api has to change (needs to be changed in the app-interface)
also updated clowder-common-ruby to get PGSSLMODE env from cdappconfig.json
---
[RHCLOUD-12241](https://issues.redhat.com/browse/RHCLOUD-12241)
> Clowder rename + PGSSLMODE variable

- app/controllers/api/v1/mixins/update_mixin.rb
- app/controllers/application_controller.rb
- app/models/application.rb
- app/models/concerns/event_concern.rb
- lib/availability_status_listener.rb
- lib/sources/api/events.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/lib/availability_status_listener_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/applications_spec.rb
- spec/requests/api/v2.0/authentications_spec.rb
- spec/requests/api/v2.0/endpoints_spec.rb
Stop sending `raise_event` for 
`Application#update`, `Endpoint#update` and `Authentication#update` when 
attributes `availability_status` or ` availability_status_error` are present in update request:
```
./api/sources/patch 'applications/1' '{"availability_status":"available"}'
./api/sources/patch 'authentications/1' '{"availability_status":"available"}'
./api/sources/patch 'endpoints/1' '{"availability_status":"available"}'
```
---
https://issues.redhat.com/browse/RHCLOUD-12860
> Allow sending raise_event only for Source#update

- app/controllers/api/v1/applications_controller.rb
- app/controllers/api/v3x1/bulk_create_controller.rb
- app/controllers/application_controller.rb
- app/models/concerns/event_concern.rb
- lib/sources/api/events.rb
- spec/lib/availability_status_listener_spec.rb
- spec/requests/api/v3.1/applications_spec.rb
- spec/requests/api/v3.1/bulk_create_spec.rb
During the integration process for superkey, I'm finding that ordering of messages is the biggest problem faced.
So I'm reworking to only raise the `Application.create` event once the superkey worker posts back. It's complicated logic, but it's necessary to make sure that the events go out in the right order:
1. `Source.create`
2. `Application.create`
3. `Authentication.create`
4. `ApplicationAuthentication.create`
\# TODO:
> Only raise Application.create events for Superkey sources when complete

- lib/sources/api/messaging.rb
Need to pass along the headers in order to make the request back to sources correctly (dummy won't work for all customers)
Needed for https://github.com/RedHatInsights/sources-superkey-worker/pull/22 to work.
> Pass along forwardable headers to superkey worker

- app/models/authentication.rb
- app/models/source.rb
- spec/lib/sources/bulk_assembly_spec.rb
- spec/models/authentication_spec.rb
- spec/models/source_spec.rb
- spec/spec_helper.rb
- spec/support/request_helper.rb
Fixing: 
- https://issues.redhat.com/browse/RHCLOUD-12897
This validation specifies that an Authentication can _only_ be attached to a Source if the `Source#app_creation_workflow` is `Source::SUPERKEY_WORKFLOW`
- https://issues.redhat.com/browse/RHCLOUD-13031
This validation makes it so the user has to disable all of the applications associated with the source before deleting the source, this is just due to the fact that if the Source gets deleted (thus cascade deleting the authentication) there is potential for dangling resources in AWS. 
This validation ensures that cannot happen, since the superkey worker will have plenty of time to clean up the resources before the Source + SuperKey Auth get deleted in the API
\# TODO:
> Add more validations when creating and destroying SuperKey Authentications

- Dockerfile
- docker-assets/entrypoint
- lib/sources/api/clowder_config.rb
Following #359. Added `jq` support for easier clowder config parsing in the shell
---
[RHCLOUD-12249](https://issues.redhat.com/browse/RHCLOUD-12249)
> Clowder Config parsed by JQ Parser

- docker-assets/entrypoint
Regarding https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT 
PGSSLROOTCERT should be a path (in opposite to clowder config, which offers content)
---
[RHCLOUD-12249](https://issues.redhat.com/browse/RHCLOUD-12249)
> PGSSLROOTCERT as a path to the cert

- app/models/application.rb
- spec/models/application_spec.rb
This appears to be what is causing the error:
```
{
"errors": [
{
"detail": "RuntimeError: Can't modify frozen hash",
"status": "400"
}
]
}
```
apparently trying to update a subresource's availability status wasn't a good idea on a destroy operation, classic. :facepalm:
cc @zsadeh
> only update availability status on superkey applications when new_record?

- grafana-dashboards/grafana-dashboard-insights-sources.configmap.yaml
Svc name on stage was changed to sources-api-svc (and prod is unchanged).
---
[RHCLOUD-13391](https://issues.redhat.com/browse/RHCLOUD-13391)
> Clowder update for grafana dashboard

- deploy/clowdapp.yaml
App-interface ServiceMonitor CRD is configured to "app: sources" label so it's needed to redefine automatic label to be able to scrape metrics.
---
[RHCLOUD-13391](https://issues.redhat.com/browse/RHCLOUD-13391)
> Add app/clowdapp labels to ClowdApp template

- app/models/concerns/event_concern.rb
- spec/controllers/api/v1x0/mixins/update_mixin_spec.rb
- spec/lib/availability_status_listener_spec.rb
- spec/requests/api/v2.0/applications_spec.rb
- spec/requests/api/v2.0/authentications_spec.rb
- spec/requests/api/v2.0/endpoints_spec.rb
Subscription Watch needs the `Application.update` messages regarding availability status. We should have validated that no one else needed them before turning them off. 
cc @syncrou
> Re-enable Application/Endpoint availability status update messages

- db/seeds/application_types.yml
https://issues.redhat.com/browse/RHCLOUD-12822
There is one issue with this combination: this combo **does not require storing any values** so I didn't create an auth type for this, instead of that I updated the UI to handle AppType+SourceType without any auth type by mocking an "empty" auth type. The UI basically injects empty auth type for this combo.
The other way is to create the empty auth type here, in source_types seed, but as I said it would be empty and it woudln't be used anywhere... and I would have to update the UI to handle empty auth types. So I think the first option is better
Let me know what you think, thanks.
> Add support for subwatch + azure

- Dockerfile
mimemagic gem requires shared-mime-types database installed on the system (part of rails)
---
https://github.com/RedHatInsights/topological_inventory-api/issues/353
[RHCLOUD-13462](https://issues.redhat.com/browse/RHCLOUD-13462)
> Fix of docker image building (mimemagic)

- Gemfile
- lib/sources/api/graphql/templates/schema.erb
This configuration disable to perform introspection queries which are described [here]( https://graphql.org/learn/introspection/).
How file(`lib/sources/api/graphql/templates/schema.erb`) in this PR is loaded is described in this [PR](https://github.com/RedHatInsights/insights-api-common-rails/pull/221).
Fixes: https://issues.redhat.com/browse/RHCLOUD-11179
**WIP reason**: 
Depends on
> Disable GraphQL introspection for rails production env

- Gemfile
- config/application.rb
- config/initializers/sidekiq.rb
- deploy/clowdapp.yaml
- lib/sources/api/clowder_config.rb
This is just adding sidekiq, updated the clowdapp inline. 
I set up ActiveJob to use sidekiq as the backend as well - that way we can use standard rails generators as well as being able to change out the backend as needed. 
e2e-deploy changes for ci/qa are here: https://github.com/RedHatInsights/e2e-deploy/pull/2961
> Add Sidekiq for scheduled jobs

- config/initializers/sidekiq.rb
- lib/sources/api/clowder_config.rb
forgot to remove these defaults here - causing a crashloop in CI. 
related: https://github.com/RedHatInsights/e2e-deploy/pull/2963
> Remove defaults from initializers since they're handled in lib class

- lib/sources/api/clowder_config.rb
Fixes for sidekiq, notably:
1. We cannot send the password as `""`, that errors out on the redis end so it needs to default to nil
\# TODO: add more
> Sidekiq Fixes

- lib/sources/super_key.rb
This fixes the bug being seen on CI/Stage related to failing to delete a source. 
This is caused by the `superkey_data` field being empty on the Application, which leads to a nomethoderror when attempting to send the destroy_application request to the worker. 
It only seems to happen when the the user would create/delete a source in quick succession. Either that or when the superkey worker never posted back (which is odd - that should not be happening even on error). 
Either way, I was able to reproduce and this fixes it.
> Add check for superkey-worker completion before sending destroy_application request to worker

- db/migrate/20200422154616_rename_satellite_initial_value.rb
This change keeps migrations independent  on `app/models`.
> Use model SourceType in migration RenameSatelliteInitialValue

- Gemfile
- app/controllers/api/v3x1.rb
- app/controllers/api/v3x1/applications_controller.rb
- app/jobs/availability_message_job.rb
- app/models/application.rb
- app/models/application_authentication.rb
- app/models/authentication.rb
- app/models/concerns/availability_status_concern.rb
- app/models/concerns/pausable.rb
- app/models/source.rb
- app/policies/mixins/write_policy_mixin.rb
- config/routes.rb
- config/sidekiq.yml
- db/migrate/20210415153443_add_paused_at_columns.rb
- public/doc/openapi-3-v3.1.json
- spec/models/application_spec.rb
- spec/requests/api/v3.1/applications_spec.rb
https://issues.redhat.com/browse/RHCLOUD-9850
EDIT: 4/20/21 - this is ready to go. there is one really odd thing going on with the specs - its something to do with how AR relations form - it won't work unless I manually assign the auth to the application for the first spec. If there is a way to get around that I'm all ears!
This PR:
> Add Pause support for Applications

- app/models/application.rb
- app/models/concerns/availability_status_concern.rb
- app/models/source.rb
- spec/models/application_spec.rb
- spec/models/authentication_spec.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/sources_spec.rb
- spec/requests/api/v3.0/sources_spec.rb
- spec/requests/api/v3.1/sources_spec.rb
This PR removes sending of availability check requests to kafka -> operation workers if the Source doesn't have an endpoint.
---
[RHCLOUD-12898](https://issues.redhat.com/browse/RHCLOUD-12898)
> Application's availability check callback

- config/initializers/availability_status_listener.rb
Found this while making sure the sidekiq worker was working - basically sidekiq initializes the entire rials app when it starts up, and we do _not_ want multiple listeners running since that could get confusing if we need to debug it ever. 
This PR adds a constraint to the listener so it only runs the pod in non-sidekiq hostname situations. I tried to think of another way, but didn't really want to add another ENV var to say "run listener" and the like. 
Open to suggestions if there are any since I know this isn't entirely clean.
> Only start availability_status_listener in the main sources-api pod

- app/models/concerns/tenancy_concern.rb
Regarding https://github.com/ErwinM/acts_as_tenant#belongs_to-options
the `belongs_to` was duplicated
> Remove redundant tenant relation

- app/models/concerns/event_concern.rb
Fixes the error in the response when using bulk-create to create a superkey source - the bulk message functionality errored out on the message produce even though the objects were still created.
> fix bulk_message to handle when an authentication is attached to a source

- lib/availability_status_listener.rb
So I just noticed this on prod - the listener apparently lost connection to the db and since it's just running in a thread it apparently doesn't manually reconnect. 
The little handler there tries to re-establish the connection before failing _again_ and being caught by the final rescue clause again. This way if it's just a blip it'll reconnect and retry.
> Retry connecting to the db if the listener runs into a connection error

- app/models/application.rb
- spec/models/application_spec.rb
I totally forgot that I refactored that job after doing this section of the code - resulting in the callback straight up _not working_ when just deleting an application.
Deleting a Source (and all sub-applications) works fine, but deleting just an individual application doesn't work. This fixes that.
> Fix application delete for SuperKey Sources

- app/jobs/kafka_publish_job.rb
- app/models/source.rb
- spec/jobs/kafka_publish_job_spec.rb
- spec/rails_helper.rb
- spec/requests/api/v1.0/sources_spec.rb
- spec/requests/api/v2.0/sources_spec.rb
- spec/requests/api/v3.0/sources_spec.rb
- spec/requests/api/v3.1/sources_spec.rb
Moar hackathon work...
the `POST /sources/:id/check_availability` operation can slow to an absolute crawl during the sources-monitor runs mostly due to the fact that it's producing a message for every source, which can balloon the average request time to 1-2 seconds.
By queuing them in sidekiq we can process them in parallel and most importantly *out of the request* so the request time is still wicked fast. 
cc @syncrou 
EDIT: I imported the CI db locally and ran a test to see how much faster this will be - I ran both checkers like so: 
```
time bash -c "bundle exec bin/availability_checker available && bundle exec bin/availability_checker unavailable" >/dev/null
```
the results are as such:
old code (produce message in the request): 
```
real    0m22.084s
user    0m1.631s 
sys …
```
> Add sidekiq job for requesting endpoint availability

- Gemfile
- app/jobs/availability_status_update_job.rb
- deploy/clowdapp.yaml
- lib/availability_status_listener.rb
- spec/jobs/availability_status_update_job_spec.rb
- spec/lib/availability_status_listener_spec.rb
This is part of my hackathon work!
Basically moving the availability status listener's guts into a sidekiq job - so we can process more of them than one at a time. The biggest problem before was that we processed the update messages serially - so it could take quite a while to process if a bunch of them came back at once. This way we can increase the number of sidekiq workers and process them as fast as we want. 
cc @syncrou
> Add Sidekiq job for availability message processing

- app/controllers/internal/v2x0/mixins/index_mixin.rb
- app/controllers/internal/v2x0/mixins/open_api_mixin.rb
- app/controllers/internal/v2x0/sources_controller.rb
- config/routes.rb
- private/doc/openapi-3-v2.0.json
- spec/controllers/internal/v2x0/index_mixin_spec.rb
- spec/swagger_spec.rb
Primary usage of the internal/v2.0/sources is by SourcesMonitor cronjobs to avoid tenant based multiple queries.
Btw (not related to this PR) I found either insights-api-common or acts-as-tenant are introducing N+1 queries problem when requesting Source.all (in both this and public SourcesController)
---
[RHCLOUD-14101](https://issues.redhat.com/browse/RHCLOUD-14101)
> Internal SourcesController

- app/controllers/api/v3x1/applications_controller.rb
- app/controllers/api/v3x1/sources_controller.rb
- app/controllers/application_controller.rb
- app/jobs/async_delete_job.rb
- app/jobs/superkey_delete_job.rb
- app/models/concerns/event_concern.rb
- app/policies/default_policy.rb
- lib/sources/api/messaging.rb
- lib/sources/api/request.rb
- spec/requests/api/rbac_spec.rb
https://issues.redhat.com/browse/RHCLOUD-12955
\# TODO:
**EDIT:** So, the biggest part about this is that we probably need to have backward compatibility with the x-rh-id header + the new PSK related headers. 
To get around this I overrode the `Insights::API::Common::Request.current_forwardable` class method to add any new fields we want to - currently just forwarding the account number since they will have the PSK mounted as a secret in their namespace. 
----
I am probably going to do the kafka availability status listener changes (no more required x-rh-id header, required account number) in a separate PR that way this one doesn't get huge. 
So this PR basically just adds internal communication via PSK and passes on the new headers when they are used.
> Add PSK support

- db/seeds/application_types.yml
- spec/models/application_type_spec.rb
Only question I have here - if it deletes the application type will it cascade delete all the applications in the DB that are topo?
EDIT:
Yep, looks like it does. 
```
[ remove_topo_application_type ⚛ ] ~/git/crc/sources/api $ rails c
Loading development environment (Rails 5.2.6)
[1] pry(main)> Application.count
(0.4ms)  SELECT COUNT(*) FROM "applications"
=> 85
((( rake db:seed in another terminal )))
[2] pry(main)> Application.count
(0.4ms)  SELECT COUNT(*) FROM "applications"
=> 76
```
> Remove Topological Inventory ApplicationType

- app/models/authentication.rb
- spec/models/authentication_spec.rb
https://issues.redhat.com/browse/RHCLOUD-14557
API side implmenetation for this bug - for superkey we _NEED_ both username and password (access/secret keys in the case of AWS). This PR just adds a validation on that for superkey sources. 
We may need to revisit this in the future if there is a source type that only requires one, like an API key or something.
> require both username + password on superkey authentications

- Gemfile
5.0.5 includes Support total counts for GraphQL https://github.com/RedHatInsights/insights-api-common-rails/pull/229
> Bump insights api common to 5.0.5

- deploy/clowdapp.yaml
https://issues.redhat.com/browse/RHCLOUD-14651
Clowdapp change for ^, the `optional: true` denotion basically says "still spin up the deployment even if the secret isn't there, otherwise we would end up with a pod initialization error.
> Add support for SOURCES_PSKS secret if it exists in the namespace

- app/policies/default_policy.rb
Me being the derp that I am edited it to plural `PSKS` everywhere except the actual code.
> pluralize SOURCES_PSKS env var read in DefaultPlicy to match ENV var

- app/policies/default_policy.rb
https://issues.redhat.com/browse/RHCLOUD-15042
Last piece for RBAC 2 - we need a way to turn access via the `org_admin` off via app-interface etc.
> Check an ENV var to disable org_admin on demand

- app/models/application.rb
- app/models/endpoint.rb
- db/migrate/20210701105323_add_paused_at_to_endpoints.rb
- spec/requests/api/v3.1/applications_spec.rb
- spec/requests/api/v3.1/sources_spec.rb
- improve spec for pausing
- migration which adds `paused_at` to `endpoints` table
- changed `Aplication#[un]discard_workflow` methods to [un]discard also endpoints
> Add pausable mixin to endpoint

- app/controllers/api/v3x1.rb
- app/controllers/api/v3x1/applications_controller.rb
- app/controllers/api/v3x1/authentications_controller.rb
- app/controllers/api/v3x1/endpoints_controller.rb
- app/controllers/api/v3x1/mixins/pausable_mixin.rb
- app/controllers/api/v3x1/mixins/update_mixin.rb
- app/controllers/api/v3x1/sources_controller.rb
- public/doc/openapi-3-v3.1.json
- spec/requests/api/v3.1/applications_spec.rb
- spec/requests/api/v3.1/authentications_spec.rb
- spec/requests/api/v3.1/endpoints_spec.rb
- spec/requests/api/v3.1/sources_spec.rb
- spec/support/requests_shared_examples.rb
**WIP reason - dependent PR:** 
- done for **Authentications, Applications, Endpoints and Sources**
- Update action is still allowed for attributes(if exists on the model): `availability_status, availability_status_error, last_checked_at, last_available_at`
- Responses (if resource is paused, success as usual 204):
```
PATCH /api/sources/v3.1/applications/5
{ 
"extra": { }
}
Response 422 Multi-Status:
{
"errors": [
{
"status": "422",
"detail": "Found unpermitted parameters: extra"
}
]
}
```
```
PATCH /api/sources/v3.1/applications/5
{ 
"availability_status": "available",
"extra": { }
}
Response 207 Multi-Status:
{
"results": [
{
"detail": "Listed parameters in 'resource' has been updated successfully.",
"resource": {
"availability_status": "available"
},
"status": 200
}
],
"errors": [
{ …
```
> Disallow update action for paused resources in API

- Gemfile
- deploy/clowdapp.yaml
https://issues.redhat.com/browse/RHCLOUD-15152
`sidekiq_alive` is a nice little gem that does exactly what I was going to try and do by myself which is basically:
1. Set up a queue for monitoring completed jobs
2. If jobs are failing to get processed -> quit updating the queue
3. If the queue hasn't been updated in a while -> return a 500 on a http port
Initially i was just going to touch files (like I did in Superkey) but this gem is self contained and easy. 
cc @syncrou
> Add sidekiq_alive gem as a liveness probe for sidekiq

- Gemfile
- config/application.rb
- deploy/clowdapp.yaml
NOTE: I expect that next version of insights-api-common will be 5.0.6. But now it doesn't exists yet.
REQUIRED:
https://issues.redhat.com/browse/RHCLOUD-15151
> Use insights-logger-ruby gem through insights-api-common

- deploy/clowdapp.yaml
- lib/availability_status_listener.rb
- lib/sources/api/request.rb
A few things found while doing integration work with swatch + cost:
1. The fact that the PSK changes _on every deploy_ is kind of a PITA in reality, so I'm changing the resource to always use the same string: `thisMustBeEphemeralOrMinikube`. Open to a funnier name if you have one!
2. Cost management still needs the x-rh-identity for some of the other fields in it (who would have thought that not only the account number would be used right?) so I changed the availability status listener to not overwrite it if present.
3. And the most important oversight I made during development was that I forgot that yes, sometime stuff can come from the outside still and those requests *will not* have the `x-rh-sources-account-number` header, so we need to reach into the `x-rh-identity` and pull out the …
> Generate `x-rh-sources-account-number` header when not present

- lib/availability_status_listener.rb
- lib/sources/api/request.rb
- spec/lib/availability_status_listener_spec.rb
Fleshing this out a little more - there apparently are cases where x-rh-identity is not there but x-rh-sources-account-number is _but some want both all the time for now_. So this PR validates we have both of them on the availability status listener side as well as the forwardable headers side.
> validate that both x-rh-sources-account-number and x-rh-identity are always present.

- config/application.rb
- config/initializers/prometheus_exporter.rb
Ran into this a bunch last week - if you exec into a pod on eph or minikube there will be log messages saying "Failed to bind to port" over and over again because the pod is re-trying to setup the prometheus exporter. 
This prevents that from happening which makes `rails c`'ing into a pod cleaner.
> Skip exporting prometheus metrics if running rails console

- Gemfile
seeing this on the eph env (test failure on #446), but luckily this didn't hit stage/prod yet because we didn't promote:
```
RDS Cert Path: /opt/rdsca.crt
== Writing encryption key ==
== Checking sources-api-db.default.svc:5432 status ==
sources-api-db.default.svc:5432 - accepting connections
rake aborted!
NoMethodError: undefined method `call' for nil:NilClass
/usr/share/gems/gems/insights-loggers-ruby-0.1.10/lib/insights/loggers/container.rb:14:in `level='
/usr/share/gems/gems/manageiq-loggers-0.7.0/lib/manageiq/loggers/base.rb:13:in `initialize'
/usr/share/gems/gems/manageiq-loggers-0.7.0/lib/manageiq/loggers/container.rb:7:in `initialize'
/usr/share/gems/gems/insights-loggers-ruby-0.1.10/lib/insights/loggers/container.rb:8:in `initialize' …
```
> pin miq loggers ro 0.4.x line since 0.7.0 breaks insights-api-common container logger

- public/doc/openapi-3-v3.1.json
- spec/requests/api/v3.1/endpoints_spec.rb
Reflects the changes of [sources-api-go/pull/43](https://github.com/RedHatInsights/sources-api-go/pull/43) for the `POST /endpoints` endpoint's model.
[[RHCLOUD-16766]](https://issues.redhat.com/browse/RHCLOUD-16766)
> POST endpoint definition for "/endpoints/

- app/models/super_key_meta_data.rb
- db/migrate/20211018212220_add_source_type_to_meta_data.rb
- db/seeds/source_types.yml
- db/seeds/superkey_metadata.yml
- lib/sources/api/messaging.rb
- lib/sources/super_key.rb
Self explanatory. Did a few things:
1. Added `lighthouse` as a supported step name
2. Added a `belongs_to :source_type` to SuperKeyMetaData so we can separate steps per source type (since we only had Amazon before I didn't think of this until now). 
Other than that it follows the same patterns on superkey creation.
> Superkey changes for Azure Provider

- public/doc/openapi-3-v3.1.json
The authtype seems to be necessary when setting up an authentication object, therefore it shouldn't be readonly.
[[RHCLOUD-9262]](https://issues.redhat.com/browse/RHCLOUD-9262)
> fix: authtype should not be readonly

- db/seeds/source_types.yml
This prevents bulk_create from working - I missed it when i was pulling out all of the superkey changes for azure.
> remove 'is_superkey: true' from the lighthouse subscription authtype

- config/initializers/availability_status_listener.rb
- deploy/clowdapp.yaml
Disabling and enabling is done by environment variable `DISABLE_AVAILABILITY_STATUS_LISTENER`.
`DISABLE_AVAILABILITY_STATUS_LISTENER=true` needs to be set in order to disable availability status listener.
https://issues.redhat.com/browse/RHCLOUD-16315
> Disable availability listener by environment variable

- db/seeds/application_types.yml
- db/seeds/source_types.yml
For now, they only support AWS, so we will leave Azure aside.
[RHCLOUD-17686](https://issues.redhat.com/browse/RHCLOUD-17686)
> [RHCLOUD-17686] feature: "ROS" as an application type for the AWS source

- db/seeds/source_types.yml
Instead of having a generic "token" authentication type name which could clash with some other authentication type, by giving a unique name to these authentications processing them will be straightforward.
[RHCLOUD-17795](https://issues.redhat.com/browse/RHCLOUD-17795)
> [RHCLOUD-17795] fix: change the marketplace authentication type to "marketplace-token"

- db/seeds.rb
- deploy/clowdapp.yaml
Self explanatory. We don't need to seed on the rails side anymore due to the Go side handling it now. 
Going to add the `SKIP_SEEDING` env var to stage as well via app-interface.
> Add ability to disable seeding via ENV var, defaulting to false

- app/controllers/api/v3x1/rhc_connections_controller.rb
- app/controllers/application_controller.rb
- config/routes.rb
- deploy/clowdapp.yaml
- lib/proxy_handler.rb
- proxy_rules/default_rules.json
- spec/swagger_spec.rb
https://issues.redhat.com/browse/RHCLOUD-17970
First part of this, proxying all requests to the Go rewrite after [we merge the changes.](https://github.com/RedHatInsights/sources-api-go/pull/111) 
This negates the need for #482
> [RHCLOUD-17970] Add RHC Connection Endpoint Proxy

- deploy/clowdapp.yaml
- proxy_rules/default_rules.json
It makes sense to have the Go rewrite serving the spec, since it's the main codebase now. However, as it is not still live, we have to proxy it from the Ruby side.
[[RHCLOUD-18310]](https://issues.redhat.com/browse/RHCLOUD-18310)
> [RHCLOUD-18310] feature: proxy the OpenApi spec to the Go rewrite

- deploy/clowdapp.yaml
Makes it easier for other teams to enable or disable authenticating the
requests with RBAC if they deploy our application via AppInterface.
> RBAC bypasseable via env var

- deploy/clowdapp.yaml
- pr_check.sh
This reverts commit 37e09ac3547aa87b2f30f0fad6c633b2bc3f9591, reversing
changes made to 77e2338348601aabec20b0f0c824d26384e6bf8f.
Renaming the deployment broke *all* the smoke tests that rely on us! yay!
I've locked stage to this prior commit so it is still renamed though. Will revert this revert again once we promote to prod.
> Revert "Merge pull request #501 from lindgrenj6/rename_clowdapp"
